package relation

import (
	"github.com/openimsdk/protocol/rpccall"
	"google.golang.org/grpc"
)

func InitFriend(conn *grpc.ClientConn) {
	ApplyToAddFriendCaller.SetConn(conn)
	GetPaginationFriendsApplyToCaller.SetConn(conn)
	GetPaginationFriendsApplyFromCaller.SetConn(conn)
	GetDesignatedFriendsApplyCaller.SetConn(conn)
	GetIncrementalFriendsApplyToCaller.SetConn(conn)
	GetIncrementalFriendsApplyFromCaller.SetConn(conn)
	AddBlackCaller.SetConn(conn)
	RemoveBlackCaller.SetConn(conn)
	IsFriendCaller.SetConn(conn)
	IsBlackCaller.SetConn(conn)
	GetPaginationBlacksCaller.SetConn(conn)
	GetSpecifiedBlacksCaller.SetConn(conn)
	DeleteFriendCaller.SetConn(conn)
	RespondFriendApplyCaller.SetConn(conn)
	UpdateFriendsCaller.SetConn(conn)
	SetFriendRemarkCaller.SetConn(conn)
	ImportFriendsCaller.SetConn(conn)
	GetDesignatedFriendsCaller.SetConn(conn)
	GetPaginationFriendsCaller.SetConn(conn)
	GetFriendIDsCaller.SetConn(conn)
	GetSpecifiedFriendsInfoCaller.SetConn(conn)
	GetIncrementalFriendsCaller.SetConn(conn)
	GetIncrementalBlacksCaller.SetConn(conn)
	GetFullFriendUserIDsCaller.SetConn(conn)
	NotificationUserInfoUpdateCaller.SetConn(conn)
	GetFriendInfoCaller.SetConn(conn)
}

var (
	ApplyToAddFriendCaller               = rpccall.NewRpcCaller[ApplyToAddFriendReq, ApplyToAddFriendResp](Friend_ApplyToAddFriend_FullMethodName)
	GetPaginationFriendsApplyToCaller    = rpccall.NewRpcCaller[GetPaginationFriendsApplyToReq, GetPaginationFriendsApplyToResp](Friend_GetPaginationFriendsApplyTo_FullMethodName)
	GetPaginationFriendsApplyFromCaller  = rpccall.NewRpcCaller[GetPaginationFriendsApplyFromReq, GetPaginationFriendsApplyFromResp](Friend_GetPaginationFriendsApplyFrom_FullMethodName)
	GetDesignatedFriendsApplyCaller      = rpccall.NewRpcCaller[GetDesignatedFriendsApplyReq, GetDesignatedFriendsApplyResp](Friend_GetDesignatedFriendsApply_FullMethodName)
	GetIncrementalFriendsApplyToCaller   = rpccall.NewRpcCaller[GetIncrementalFriendsApplyToReq, GetIncrementalFriendsApplyToResp](Friend_GetIncrementalFriendsApplyTo_FullMethodName)
	GetIncrementalFriendsApplyFromCaller = rpccall.NewRpcCaller[GetIncrementalFriendsApplyFromReq, GetIncrementalFriendsApplyFromResp](Friend_GetIncrementalFriendsApplyFrom_FullMethodName)
	AddBlackCaller                       = rpccall.NewRpcCaller[AddBlackReq, AddBlackResp](Friend_AddBlack_FullMethodName)
	RemoveBlackCaller                    = rpccall.NewRpcCaller[RemoveBlackReq, RemoveBlackResp](Friend_RemoveBlack_FullMethodName)
	IsFriendCaller                       = rpccall.NewRpcCaller[IsFriendReq, IsFriendResp](Friend_IsFriend_FullMethodName)
	IsBlackCaller                        = rpccall.NewRpcCaller[IsBlackReq, IsBlackResp](Friend_IsBlack_FullMethodName)
	GetPaginationBlacksCaller            = rpccall.NewRpcCaller[GetPaginationBlacksReq, GetPaginationBlacksResp](Friend_GetPaginationBlacks_FullMethodName)
	GetSpecifiedBlacksCaller             = rpccall.NewRpcCaller[GetSpecifiedBlacksReq, GetSpecifiedBlacksResp](Friend_GetSpecifiedBlacks_FullMethodName)
	DeleteFriendCaller                   = rpccall.NewRpcCaller[DeleteFriendReq, DeleteFriendResp](Friend_DeleteFriend_FullMethodName)
	RespondFriendApplyCaller             = rpccall.NewRpcCaller[RespondFriendApplyReq, RespondFriendApplyResp](Friend_RespondFriendApply_FullMethodName)
	UpdateFriendsCaller                  = rpccall.NewRpcCaller[UpdateFriendsReq, UpdateFriendsResp](Friend_UpdateFriends_FullMethodName)
	SetFriendRemarkCaller                = rpccall.NewRpcCaller[SetFriendRemarkReq, SetFriendRemarkResp](Friend_SetFriendRemark_FullMethodName)
	ImportFriendsCaller                  = rpccall.NewRpcCaller[ImportFriendReq, ImportFriendResp](Friend_ImportFriends_FullMethodName)
	GetDesignatedFriendsCaller           = rpccall.NewRpcCaller[GetDesignatedFriendsReq, GetDesignatedFriendsResp](Friend_GetDesignatedFriends_FullMethodName)
	GetPaginationFriendsCaller           = rpccall.NewRpcCaller[GetPaginationFriendsReq, GetPaginationFriendsResp](Friend_GetPaginationFriends_FullMethodName)
	GetFriendIDsCaller                   = rpccall.NewRpcCaller[GetFriendIDsReq, GetFriendIDsResp](Friend_GetFriendIDs_FullMethodName)
	GetSpecifiedFriendsInfoCaller        = rpccall.NewRpcCaller[GetSpecifiedFriendsInfoReq, GetSpecifiedFriendsInfoResp](Friend_GetSpecifiedFriendsInfo_FullMethodName)
	GetIncrementalFriendsCaller          = rpccall.NewRpcCaller[GetIncrementalFriendsReq, GetIncrementalFriendsResp](Friend_GetIncrementalFriends_FullMethodName)
	GetIncrementalBlacksCaller           = rpccall.NewRpcCaller[GetIncrementalBlacksReq, GetIncrementalBlacksResp](Friend_GetIncrementalBlacks_FullMethodName)
	GetFullFriendUserIDsCaller           = rpccall.NewRpcCaller[GetFullFriendUserIDsReq, GetFullFriendUserIDsResp](Friend_GetFullFriendUserIDs_FullMethodName)
	NotificationUserInfoUpdateCaller     = rpccall.NewRpcCaller[NotificationUserInfoUpdateReq, NotificationUserInfoUpdateResp](Friend_NotificationUserInfoUpdate_FullMethodName)
	GetFriendInfoCaller                  = rpccall.NewRpcCaller[GetFriendInfoReq, GetFriendInfoResp](Friend_GetFriendInfo_FullMethodName)
)
