protoc --go_out=plugins=grpc:./auth --go_opt=module=github.com/openimsdk/protocol/auth auth/auth.proto
protoc --go_out=plugins=grpc:./conversation --go_opt=module=github.com/openimsdk/protocol/conversation conversation/conversation.proto
protoc --go_out=plugins=grpc:./errinfo --go_opt=module=github.com/openimsdk/protocol/errinfo errinfo/errinfo.proto
protoc --go_out=plugins=grpc:./friend --go_opt=module=github.com/openimsdk/protocol/friend friend/friend.proto
protoc --go_out=plugins=grpc:./group --go_opt=module=github.com/openimsdk/protocol/group group/group.proto
protoc --go_out=plugins=grpc:./msg --go_opt=module=github.com/openimsdk/protocol/msg msg/msg.proto
protoc --go_out=plugins=grpc:./msggateway --go_opt=module=github.com/openimsdk/protocol/msggateway msggateway/msggateway.proto
protoc --go_out=plugins=grpc:./push --go_opt=module=github.com/openimsdk/protocol/push push/push.proto
protoc --go_out=plugins=grpc:./rtc --go_opt=module=github.com/openimsdk/protocol/rtc rtc/rtc.proto
protoc --go_out=plugins=grpc:./sdkws --go_opt=module=github.com/openimsdk/protocol/sdkws sdkws/sdkws.proto
protoc --go_out=plugins=grpc:./third --go_opt=module=github.com/openimsdk/protocol/third third/third.proto
protoc --go_out=plugins=grpc:./user --go_opt=module=github.com/openimsdk/protocol/user user/user.proto
protoc --go_out=plugins=grpc:./statistics --go_opt=module=github.com/openimsdk/protocol/statistics statistics/statistics.proto