package group

import (
	"github.com/openimsdk/protocol/rpccall"
	"google.golang.org/grpc"
)

func InitGroup(conn *grpc.ClientConn) {
	CreateGroupCaller.SetConn(conn)
	JoinGroupCaller.SetConn(conn)
	QuitGroupCaller.SetConn(conn)
	GetGroupsInfoCaller.SetConn(conn)
	SetGroupInfoCaller.SetConn(conn)
	SetGroupInfoExCaller.SetConn(conn)
	GetGroupApplicationListCaller.SetConn(conn)
	GetUserReqApplicationListCaller.SetConn(conn)
	GetGroupUsersReqApplicationListCaller.SetConn(conn)
	GetSpecifiedUserGroupRequestInfoCaller.SetConn(conn)
	TransferGroupOwnerCaller.SetConn(conn)
	GroupApplicationResponseCaller.SetConn(conn)
	GetGroupMemberListCaller.SetConn(conn)
	GetGroupMembersInfoCaller.SetConn(conn)
	KickGroupMemberCaller.SetConn(conn)
	GetJoinedGroupListCaller.SetConn(conn)
	InviteUserToGroupCaller.SetConn(conn)
	GetGroupsCaller.SetConn(conn)
	GetGroupMembersCMSCaller.SetConn(conn)
	DismissGroupCaller.SetConn(conn)
	MuteGroupMemberCaller.SetConn(conn)
	CancelMuteGroupMemberCaller.SetConn(conn)
	MuteGroupCaller.SetConn(conn)
	CancelMuteGroupCaller.SetConn(conn)
	SetGroupMemberInfoCaller.SetConn(conn)
	GetGroupAbstractInfoCaller.SetConn(conn)
	GetUserInGroupMembersCaller.SetConn(conn)
	GetGroupMemberUserIDsCaller.SetConn(conn)
	GetGroupMemberRoleLevelCaller.SetConn(conn)
	GetGroupInfoCacheCaller.SetConn(conn)
	GetGroupMemberCacheCaller.SetConn(conn)
	GroupCreateCountCaller.SetConn(conn)
	NotificationUserInfoUpdateCaller.SetConn(conn)
	GetIncrementalGroupMemberCaller.SetConn(conn)
	BatchGetIncrementalGroupMemberCaller.SetConn(conn)
	GetIncrementalJoinGroupCaller.SetConn(conn)
	GetFullGroupMemberUserIDsCaller.SetConn(conn)
	GetFullJoinGroupIDsCaller.SetConn(conn)
}

var (
	CreateGroupCaller                      = rpccall.NewRpcCaller[CreateGroupReq, CreateGroupResp](Group_CreateGroup_FullMethodName)
	JoinGroupCaller                        = rpccall.NewRpcCaller[JoinGroupReq, JoinGroupResp](Group_JoinGroup_FullMethodName)
	QuitGroupCaller                        = rpccall.NewRpcCaller[QuitGroupReq, QuitGroupResp](Group_QuitGroup_FullMethodName)
	GetGroupsInfoCaller                    = rpccall.NewRpcCaller[GetGroupsInfoReq, GetGroupsInfoResp](Group_GetGroupsInfo_FullMethodName)
	SetGroupInfoCaller                     = rpccall.NewRpcCaller[SetGroupInfoReq, SetGroupInfoResp](Group_SetGroupInfo_FullMethodName)
	SetGroupInfoExCaller                   = rpccall.NewRpcCaller[SetGroupInfoExReq, SetGroupInfoExResp](Group_SetGroupInfoEx_FullMethodName)
	GetGroupApplicationListCaller          = rpccall.NewRpcCaller[GetGroupApplicationListReq, GetGroupApplicationListResp](Group_GetGroupApplicationList_FullMethodName)
	GetUserReqApplicationListCaller        = rpccall.NewRpcCaller[GetUserReqApplicationListReq, GetUserReqApplicationListResp](Group_GetUserReqApplicationList_FullMethodName)
	GetGroupUsersReqApplicationListCaller  = rpccall.NewRpcCaller[GetGroupUsersReqApplicationListReq, GetGroupUsersReqApplicationListResp](Group_GetGroupUsersReqApplicationList_FullMethodName)
	GetSpecifiedUserGroupRequestInfoCaller = rpccall.NewRpcCaller[GetSpecifiedUserGroupRequestInfoReq, GetSpecifiedUserGroupRequestInfoResp](Group_GetSpecifiedUserGroupRequestInfo_FullMethodName)
	TransferGroupOwnerCaller               = rpccall.NewRpcCaller[TransferGroupOwnerReq, TransferGroupOwnerResp](Group_TransferGroupOwner_FullMethodName)
	GroupApplicationResponseCaller         = rpccall.NewRpcCaller[GroupApplicationResponseReq, GroupApplicationResponseResp](Group_GroupApplicationResponse_FullMethodName)
	GetGroupMemberListCaller               = rpccall.NewRpcCaller[GetGroupMemberListReq, GetGroupMemberListResp](Group_GetGroupMemberList_FullMethodName)
	GetGroupMembersInfoCaller              = rpccall.NewRpcCaller[GetGroupMembersInfoReq, GetGroupMembersInfoResp](Group_GetGroupMembersInfo_FullMethodName)
	KickGroupMemberCaller                  = rpccall.NewRpcCaller[KickGroupMemberReq, KickGroupMemberResp](Group_KickGroupMember_FullMethodName)
	GetJoinedGroupListCaller               = rpccall.NewRpcCaller[GetJoinedGroupListReq, GetJoinedGroupListResp](Group_GetJoinedGroupList_FullMethodName)
	InviteUserToGroupCaller                = rpccall.NewRpcCaller[InviteUserToGroupReq, InviteUserToGroupResp](Group_InviteUserToGroup_FullMethodName)
	GetGroupsCaller                        = rpccall.NewRpcCaller[GetGroupsReq, GetGroupsResp](Group_GetGroups_FullMethodName)
	GetGroupMembersCMSCaller               = rpccall.NewRpcCaller[GetGroupMembersCMSReq, GetGroupMembersCMSResp](Group_GetGroupMembersCMS_FullMethodName)
	DismissGroupCaller                     = rpccall.NewRpcCaller[DismissGroupReq, DismissGroupResp](Group_DismissGroup_FullMethodName)
	MuteGroupMemberCaller                  = rpccall.NewRpcCaller[MuteGroupMemberReq, MuteGroupMemberResp](Group_MuteGroupMember_FullMethodName)
	CancelMuteGroupMemberCaller            = rpccall.NewRpcCaller[CancelMuteGroupMemberReq, CancelMuteGroupMemberResp](Group_CancelMuteGroupMember_FullMethodName)
	MuteGroupCaller                        = rpccall.NewRpcCaller[MuteGroupReq, MuteGroupResp](Group_MuteGroup_FullMethodName)
	CancelMuteGroupCaller                  = rpccall.NewRpcCaller[CancelMuteGroupReq, CancelMuteGroupResp](Group_CancelMuteGroup_FullMethodName)
	SetGroupMemberInfoCaller               = rpccall.NewRpcCaller[SetGroupMemberInfoReq, SetGroupMemberInfoResp](Group_SetGroupMemberInfo_FullMethodName)
	GetGroupAbstractInfoCaller             = rpccall.NewRpcCaller[GetGroupAbstractInfoReq, GetGroupAbstractInfoResp](Group_GetGroupAbstractInfo_FullMethodName)
	GetUserInGroupMembersCaller            = rpccall.NewRpcCaller[GetUserInGroupMembersReq, GetUserInGroupMembersResp](Group_GetUserInGroupMembers_FullMethodName)
	GetGroupMemberUserIDsCaller            = rpccall.NewRpcCaller[GetGroupMemberUserIDsReq, GetGroupMemberUserIDsResp](Group_GetGroupMemberUserIDs_FullMethodName)
	GetGroupMemberRoleLevelCaller          = rpccall.NewRpcCaller[GetGroupMemberRoleLevelReq, GetGroupMemberRoleLevelResp](Group_GetGroupMemberRoleLevel_FullMethodName)
	GetGroupInfoCacheCaller                = rpccall.NewRpcCaller[GetGroupInfoCacheReq, GetGroupInfoCacheResp](Group_GetGroupInfoCache_FullMethodName)
	GetGroupMemberCacheCaller              = rpccall.NewRpcCaller[GetGroupMemberCacheReq, GetGroupMemberCacheResp](Group_GetGroupMemberCache_FullMethodName)
	GroupCreateCountCaller                 = rpccall.NewRpcCaller[GroupCreateCountReq, GroupCreateCountResp](Group_GroupCreateCount_FullMethodName)
	NotificationUserInfoUpdateCaller       = rpccall.NewRpcCaller[NotificationUserInfoUpdateReq, NotificationUserInfoUpdateResp](Group_NotificationUserInfoUpdate_FullMethodName)
	GetIncrementalGroupMemberCaller        = rpccall.NewRpcCaller[GetIncrementalGroupMemberReq, GetIncrementalGroupMemberResp](Group_GetIncrementalGroupMember_FullMethodName)
	BatchGetIncrementalGroupMemberCaller   = rpccall.NewRpcCaller[BatchGetIncrementalGroupMemberReq, BatchGetIncrementalGroupMemberResp](Group_BatchGetIncrementalGroupMember_FullMethodName)
	GetIncrementalJoinGroupCaller          = rpccall.NewRpcCaller[GetIncrementalJoinGroupReq, GetIncrementalJoinGroupResp](Group_GetIncrementalJoinGroup_FullMethodName)
	GetFullGroupMemberUserIDsCaller        = rpccall.NewRpcCaller[GetFullGroupMemberUserIDsReq, GetFullGroupMemberUserIDsResp](Group_GetFullGroupMemberUserIDs_FullMethodName)
	GetFullJoinGroupIDsCaller              = rpccall.NewRpcCaller[GetFullJoinGroupIDsReq, GetFullJoinGroupIDsResp](Group_GetFullJoinGroupIDs_FullMethodName)
)
