// Copyright © 2023 OpenIM. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: msggateway/msggateway.proto

package msggateway

import (
	sdkws "github.com/openimsdk/protocol/sdkws"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OnlinePushMsgReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgData       *sdkws.MsgData         `protobuf:"bytes,1,opt,name=msgData,proto3" json:"msgData"`
	PushToUserID  string                 `protobuf:"bytes,2,opt,name=pushToUserID,proto3" json:"pushToUserID"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnlinePushMsgReq) Reset() {
	*x = OnlinePushMsgReq{}
	mi := &file_msggateway_msggateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnlinePushMsgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlinePushMsgReq) ProtoMessage() {}

func (x *OnlinePushMsgReq) ProtoReflect() protoreflect.Message {
	mi := &file_msggateway_msggateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlinePushMsgReq.ProtoReflect.Descriptor instead.
func (*OnlinePushMsgReq) Descriptor() ([]byte, []int) {
	return file_msggateway_msggateway_proto_rawDescGZIP(), []int{0}
}

func (x *OnlinePushMsgReq) GetMsgData() *sdkws.MsgData {
	if x != nil {
		return x.MsgData
	}
	return nil
}

func (x *OnlinePushMsgReq) GetPushToUserID() string {
	if x != nil {
		return x.PushToUserID
	}
	return ""
}

type OnlinePushMsgResp struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Resp          []*SingleMsgToUserPlatform `protobuf:"bytes,1,rep,name=resp,proto3" json:"resp"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnlinePushMsgResp) Reset() {
	*x = OnlinePushMsgResp{}
	mi := &file_msggateway_msggateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnlinePushMsgResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlinePushMsgResp) ProtoMessage() {}

func (x *OnlinePushMsgResp) ProtoReflect() protoreflect.Message {
	mi := &file_msggateway_msggateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlinePushMsgResp.ProtoReflect.Descriptor instead.
func (*OnlinePushMsgResp) Descriptor() ([]byte, []int) {
	return file_msggateway_msggateway_proto_rawDescGZIP(), []int{1}
}

func (x *OnlinePushMsgResp) GetResp() []*SingleMsgToUserPlatform {
	if x != nil {
		return x.Resp
	}
	return nil
}

type SingleMsgToUserResults struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	UserID        string                     `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID"`
	Resp          []*SingleMsgToUserPlatform `protobuf:"bytes,2,rep,name=resp,proto3" json:"resp"`
	OnlinePush    bool                       `protobuf:"varint,3,opt,name=onlinePush,proto3" json:"onlinePush"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SingleMsgToUserResults) Reset() {
	*x = SingleMsgToUserResults{}
	mi := &file_msggateway_msggateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SingleMsgToUserResults) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleMsgToUserResults) ProtoMessage() {}

func (x *SingleMsgToUserResults) ProtoReflect() protoreflect.Message {
	mi := &file_msggateway_msggateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleMsgToUserResults.ProtoReflect.Descriptor instead.
func (*SingleMsgToUserResults) Descriptor() ([]byte, []int) {
	return file_msggateway_msggateway_proto_rawDescGZIP(), []int{2}
}

func (x *SingleMsgToUserResults) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *SingleMsgToUserResults) GetResp() []*SingleMsgToUserPlatform {
	if x != nil {
		return x.Resp
	}
	return nil
}

func (x *SingleMsgToUserResults) GetOnlinePush() bool {
	if x != nil {
		return x.OnlinePush
	}
	return false
}

type OnlineBatchPushOneMsgReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgData       *sdkws.MsgData         `protobuf:"bytes,1,opt,name=msgData,proto3" json:"msgData"`
	PushToUserIDs []string               `protobuf:"bytes,2,rep,name=pushToUserIDs,proto3" json:"pushToUserIDs"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnlineBatchPushOneMsgReq) Reset() {
	*x = OnlineBatchPushOneMsgReq{}
	mi := &file_msggateway_msggateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnlineBatchPushOneMsgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineBatchPushOneMsgReq) ProtoMessage() {}

func (x *OnlineBatchPushOneMsgReq) ProtoReflect() protoreflect.Message {
	mi := &file_msggateway_msggateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineBatchPushOneMsgReq.ProtoReflect.Descriptor instead.
func (*OnlineBatchPushOneMsgReq) Descriptor() ([]byte, []int) {
	return file_msggateway_msggateway_proto_rawDescGZIP(), []int{3}
}

func (x *OnlineBatchPushOneMsgReq) GetMsgData() *sdkws.MsgData {
	if x != nil {
		return x.MsgData
	}
	return nil
}

func (x *OnlineBatchPushOneMsgReq) GetPushToUserIDs() []string {
	if x != nil {
		return x.PushToUserIDs
	}
	return nil
}

type OnlineBatchPushOneMsgResp struct {
	state            protoimpl.MessageState    `protogen:"open.v1"`
	SinglePushResult []*SingleMsgToUserResults `protobuf:"bytes,1,rep,name=singlePushResult,proto3" json:"singlePushResult"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *OnlineBatchPushOneMsgResp) Reset() {
	*x = OnlineBatchPushOneMsgResp{}
	mi := &file_msggateway_msggateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnlineBatchPushOneMsgResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineBatchPushOneMsgResp) ProtoMessage() {}

func (x *OnlineBatchPushOneMsgResp) ProtoReflect() protoreflect.Message {
	mi := &file_msggateway_msggateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineBatchPushOneMsgResp.ProtoReflect.Descriptor instead.
func (*OnlineBatchPushOneMsgResp) Descriptor() ([]byte, []int) {
	return file_msggateway_msggateway_proto_rawDescGZIP(), []int{4}
}

func (x *OnlineBatchPushOneMsgResp) GetSinglePushResult() []*SingleMsgToUserResults {
	if x != nil {
		return x.SinglePushResult
	}
	return nil
}

type SingleMsgToUserPlatform struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ResultCode     int64                  `protobuf:"varint,1,opt,name=ResultCode,proto3" json:"ResultCode"`
	RecvID         string                 `protobuf:"bytes,2,opt,name=RecvID,proto3" json:"RecvID"`
	RecvPlatFormID int32                  `protobuf:"varint,3,opt,name=RecvPlatFormID,proto3" json:"RecvPlatFormID"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SingleMsgToUserPlatform) Reset() {
	*x = SingleMsgToUserPlatform{}
	mi := &file_msggateway_msggateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SingleMsgToUserPlatform) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleMsgToUserPlatform) ProtoMessage() {}

func (x *SingleMsgToUserPlatform) ProtoReflect() protoreflect.Message {
	mi := &file_msggateway_msggateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleMsgToUserPlatform.ProtoReflect.Descriptor instead.
func (*SingleMsgToUserPlatform) Descriptor() ([]byte, []int) {
	return file_msggateway_msggateway_proto_rawDescGZIP(), []int{5}
}

func (x *SingleMsgToUserPlatform) GetResultCode() int64 {
	if x != nil {
		return x.ResultCode
	}
	return 0
}

func (x *SingleMsgToUserPlatform) GetRecvID() string {
	if x != nil {
		return x.RecvID
	}
	return ""
}

func (x *SingleMsgToUserPlatform) GetRecvPlatFormID() int32 {
	if x != nil {
		return x.RecvPlatFormID
	}
	return 0
}

type GetUsersOnlineStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIDs       []string               `protobuf:"bytes,1,rep,name=userIDs,proto3" json:"userIDs"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersOnlineStatusReq) Reset() {
	*x = GetUsersOnlineStatusReq{}
	mi := &file_msggateway_msggateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersOnlineStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersOnlineStatusReq) ProtoMessage() {}

func (x *GetUsersOnlineStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_msggateway_msggateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersOnlineStatusReq.ProtoReflect.Descriptor instead.
func (*GetUsersOnlineStatusReq) Descriptor() ([]byte, []int) {
	return file_msggateway_msggateway_proto_rawDescGZIP(), []int{6}
}

func (x *GetUsersOnlineStatusReq) GetUserIDs() []string {
	if x != nil {
		return x.UserIDs
	}
	return nil
}

type GetUsersOnlineStatusResp struct {
	state         protoimpl.MessageState                    `protogen:"open.v1"`
	SuccessResult []*GetUsersOnlineStatusResp_SuccessResult `protobuf:"bytes,1,rep,name=successResult,proto3" json:"successResult"`
	FailedResult  []*GetUsersOnlineStatusResp_FailedDetail  `protobuf:"bytes,2,rep,name=failedResult,proto3" json:"failedResult"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersOnlineStatusResp) Reset() {
	*x = GetUsersOnlineStatusResp{}
	mi := &file_msggateway_msggateway_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersOnlineStatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersOnlineStatusResp) ProtoMessage() {}

func (x *GetUsersOnlineStatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_msggateway_msggateway_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersOnlineStatusResp.ProtoReflect.Descriptor instead.
func (*GetUsersOnlineStatusResp) Descriptor() ([]byte, []int) {
	return file_msggateway_msggateway_proto_rawDescGZIP(), []int{7}
}

func (x *GetUsersOnlineStatusResp) GetSuccessResult() []*GetUsersOnlineStatusResp_SuccessResult {
	if x != nil {
		return x.SuccessResult
	}
	return nil
}

func (x *GetUsersOnlineStatusResp) GetFailedResult() []*GetUsersOnlineStatusResp_FailedDetail {
	if x != nil {
		return x.FailedResult
	}
	return nil
}

type SingleDetail struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	UserID              string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID"`
	Status              int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status"`
	SinglePlatformToken []*SinglePlatformToken `protobuf:"bytes,3,rep,name=singlePlatformToken,proto3" json:"singlePlatformToken"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SingleDetail) Reset() {
	*x = SingleDetail{}
	mi := &file_msggateway_msggateway_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SingleDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleDetail) ProtoMessage() {}

func (x *SingleDetail) ProtoReflect() protoreflect.Message {
	mi := &file_msggateway_msggateway_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleDetail.ProtoReflect.Descriptor instead.
func (*SingleDetail) Descriptor() ([]byte, []int) {
	return file_msggateway_msggateway_proto_rawDescGZIP(), []int{8}
}

func (x *SingleDetail) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *SingleDetail) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *SingleDetail) GetSinglePlatformToken() []*SinglePlatformToken {
	if x != nil {
		return x.SinglePlatformToken
	}
	return nil
}

type SinglePlatformToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlatformID    int32                  `protobuf:"varint,1,opt,name=platformID,proto3" json:"platformID"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total"`
	Token         []string               `protobuf:"bytes,3,rep,name=token,proto3" json:"token"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SinglePlatformToken) Reset() {
	*x = SinglePlatformToken{}
	mi := &file_msggateway_msggateway_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SinglePlatformToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SinglePlatformToken) ProtoMessage() {}

func (x *SinglePlatformToken) ProtoReflect() protoreflect.Message {
	mi := &file_msggateway_msggateway_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SinglePlatformToken.ProtoReflect.Descriptor instead.
func (*SinglePlatformToken) Descriptor() ([]byte, []int) {
	return file_msggateway_msggateway_proto_rawDescGZIP(), []int{9}
}

func (x *SinglePlatformToken) GetPlatformID() int32 {
	if x != nil {
		return x.PlatformID
	}
	return 0
}

func (x *SinglePlatformToken) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SinglePlatformToken) GetToken() []string {
	if x != nil {
		return x.Token
	}
	return nil
}

type KickUserOfflineReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PlatformID     int32                  `protobuf:"varint,1,opt,name=platformID,proto3" json:"platformID"`
	KickUserIDList []string               `protobuf:"bytes,2,rep,name=kickUserIDList,proto3" json:"kickUserIDList"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *KickUserOfflineReq) Reset() {
	*x = KickUserOfflineReq{}
	mi := &file_msggateway_msggateway_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickUserOfflineReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickUserOfflineReq) ProtoMessage() {}

func (x *KickUserOfflineReq) ProtoReflect() protoreflect.Message {
	mi := &file_msggateway_msggateway_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickUserOfflineReq.ProtoReflect.Descriptor instead.
func (*KickUserOfflineReq) Descriptor() ([]byte, []int) {
	return file_msggateway_msggateway_proto_rawDescGZIP(), []int{10}
}

func (x *KickUserOfflineReq) GetPlatformID() int32 {
	if x != nil {
		return x.PlatformID
	}
	return 0
}

func (x *KickUserOfflineReq) GetKickUserIDList() []string {
	if x != nil {
		return x.KickUserIDList
	}
	return nil
}

type KickUserOfflineResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickUserOfflineResp) Reset() {
	*x = KickUserOfflineResp{}
	mi := &file_msggateway_msggateway_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickUserOfflineResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickUserOfflineResp) ProtoMessage() {}

func (x *KickUserOfflineResp) ProtoReflect() protoreflect.Message {
	mi := &file_msggateway_msggateway_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickUserOfflineResp.ProtoReflect.Descriptor instead.
func (*KickUserOfflineResp) Descriptor() ([]byte, []int) {
	return file_msggateway_msggateway_proto_rawDescGZIP(), []int{11}
}

type MultiTerminalLoginCheckReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID"`
	PlatformID    int32                  `protobuf:"varint,2,opt,name=platformID,proto3" json:"platformID"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultiTerminalLoginCheckReq) Reset() {
	*x = MultiTerminalLoginCheckReq{}
	mi := &file_msggateway_msggateway_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiTerminalLoginCheckReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiTerminalLoginCheckReq) ProtoMessage() {}

func (x *MultiTerminalLoginCheckReq) ProtoReflect() protoreflect.Message {
	mi := &file_msggateway_msggateway_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiTerminalLoginCheckReq.ProtoReflect.Descriptor instead.
func (*MultiTerminalLoginCheckReq) Descriptor() ([]byte, []int) {
	return file_msggateway_msggateway_proto_rawDescGZIP(), []int{12}
}

func (x *MultiTerminalLoginCheckReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *MultiTerminalLoginCheckReq) GetPlatformID() int32 {
	if x != nil {
		return x.PlatformID
	}
	return 0
}

func (x *MultiTerminalLoginCheckReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type MultiTerminalLoginCheckResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultiTerminalLoginCheckResp) Reset() {
	*x = MultiTerminalLoginCheckResp{}
	mi := &file_msggateway_msggateway_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiTerminalLoginCheckResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiTerminalLoginCheckResp) ProtoMessage() {}

func (x *MultiTerminalLoginCheckResp) ProtoReflect() protoreflect.Message {
	mi := &file_msggateway_msggateway_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiTerminalLoginCheckResp.ProtoReflect.Descriptor instead.
func (*MultiTerminalLoginCheckResp) Descriptor() ([]byte, []int) {
	return file_msggateway_msggateway_proto_rawDescGZIP(), []int{13}
}

type GetUsersOnlineStatusResp_SuccessDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlatformID    int32                  `protobuf:"varint,1,opt,name=platformID,proto3" json:"platformID"`
	ConnID        string                 `protobuf:"bytes,2,opt,name=connID,proto3" json:"connID"`
	IsBackground  bool                   `protobuf:"varint,3,opt,name=isBackground,proto3" json:"isBackground"`
	Token         string                 `protobuf:"bytes,4,opt,name=token,proto3" json:"token"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersOnlineStatusResp_SuccessDetail) Reset() {
	*x = GetUsersOnlineStatusResp_SuccessDetail{}
	mi := &file_msggateway_msggateway_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersOnlineStatusResp_SuccessDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersOnlineStatusResp_SuccessDetail) ProtoMessage() {}

func (x *GetUsersOnlineStatusResp_SuccessDetail) ProtoReflect() protoreflect.Message {
	mi := &file_msggateway_msggateway_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersOnlineStatusResp_SuccessDetail.ProtoReflect.Descriptor instead.
func (*GetUsersOnlineStatusResp_SuccessDetail) Descriptor() ([]byte, []int) {
	return file_msggateway_msggateway_proto_rawDescGZIP(), []int{7, 0}
}

func (x *GetUsersOnlineStatusResp_SuccessDetail) GetPlatformID() int32 {
	if x != nil {
		return x.PlatformID
	}
	return 0
}

func (x *GetUsersOnlineStatusResp_SuccessDetail) GetConnID() string {
	if x != nil {
		return x.ConnID
	}
	return ""
}

func (x *GetUsersOnlineStatusResp_SuccessDetail) GetIsBackground() bool {
	if x != nil {
		return x.IsBackground
	}
	return false
}

func (x *GetUsersOnlineStatusResp_SuccessDetail) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetUsersOnlineStatusResp_FailedDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersOnlineStatusResp_FailedDetail) Reset() {
	*x = GetUsersOnlineStatusResp_FailedDetail{}
	mi := &file_msggateway_msggateway_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersOnlineStatusResp_FailedDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersOnlineStatusResp_FailedDetail) ProtoMessage() {}

func (x *GetUsersOnlineStatusResp_FailedDetail) ProtoReflect() protoreflect.Message {
	mi := &file_msggateway_msggateway_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersOnlineStatusResp_FailedDetail.ProtoReflect.Descriptor instead.
func (*GetUsersOnlineStatusResp_FailedDetail) Descriptor() ([]byte, []int) {
	return file_msggateway_msggateway_proto_rawDescGZIP(), []int{7, 1}
}

func (x *GetUsersOnlineStatusResp_FailedDetail) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type GetUsersOnlineStatusResp_SuccessResult struct {
	state                protoimpl.MessageState                    `protogen:"open.v1"`
	UserID               string                                    `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID"`
	Status               int32                                     `protobuf:"varint,2,opt,name=status,proto3" json:"status"`
	DetailPlatformStatus []*GetUsersOnlineStatusResp_SuccessDetail `protobuf:"bytes,3,rep,name=detailPlatformStatus,proto3" json:"detailPlatformStatus"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetUsersOnlineStatusResp_SuccessResult) Reset() {
	*x = GetUsersOnlineStatusResp_SuccessResult{}
	mi := &file_msggateway_msggateway_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersOnlineStatusResp_SuccessResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersOnlineStatusResp_SuccessResult) ProtoMessage() {}

func (x *GetUsersOnlineStatusResp_SuccessResult) ProtoReflect() protoreflect.Message {
	mi := &file_msggateway_msggateway_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersOnlineStatusResp_SuccessResult.ProtoReflect.Descriptor instead.
func (*GetUsersOnlineStatusResp_SuccessResult) Descriptor() ([]byte, []int) {
	return file_msggateway_msggateway_proto_rawDescGZIP(), []int{7, 2}
}

func (x *GetUsersOnlineStatusResp_SuccessResult) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *GetUsersOnlineStatusResp_SuccessResult) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetUsersOnlineStatusResp_SuccessResult) GetDetailPlatformStatus() []*GetUsersOnlineStatusResp_SuccessDetail {
	if x != nil {
		return x.DetailPlatformStatus
	}
	return nil
}

var File_msggateway_msggateway_proto protoreflect.FileDescriptor

const file_msggateway_msggateway_proto_rawDesc = "" +
	"\n" +
	"\x1bmsggateway/msggateway.proto\x12\x11openim.msggateway\x1a\x11sdkws/sdkws.proto\"g\n" +
	"\x10OnlinePushMsgReq\x12/\n" +
	"\amsgData\x18\x01 \x01(\v2\x15.openim.sdkws.MsgDataR\amsgData\x12\"\n" +
	"\fpushToUserID\x18\x02 \x01(\tR\fpushToUserID\"S\n" +
	"\x11OnlinePushMsgResp\x12>\n" +
	"\x04resp\x18\x01 \x03(\v2*.openim.msggateway.SingleMsgToUserPlatformR\x04resp\"\x90\x01\n" +
	"\x16SingleMsgToUserResults\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\x12>\n" +
	"\x04resp\x18\x02 \x03(\v2*.openim.msggateway.SingleMsgToUserPlatformR\x04resp\x12\x1e\n" +
	"\n" +
	"onlinePush\x18\x03 \x01(\bR\n" +
	"onlinePush\"q\n" +
	"\x18OnlineBatchPushOneMsgReq\x12/\n" +
	"\amsgData\x18\x01 \x01(\v2\x15.openim.sdkws.MsgDataR\amsgData\x12$\n" +
	"\rpushToUserIDs\x18\x02 \x03(\tR\rpushToUserIDs\"r\n" +
	"\x19OnlineBatchPushOneMsgResp\x12U\n" +
	"\x10singlePushResult\x18\x01 \x03(\v2).openim.msggateway.SingleMsgToUserResultsR\x10singlePushResult\"y\n" +
	"\x17SingleMsgToUserPlatform\x12\x1e\n" +
	"\n" +
	"ResultCode\x18\x01 \x01(\x03R\n" +
	"ResultCode\x12\x16\n" +
	"\x06RecvID\x18\x02 \x01(\tR\x06RecvID\x12&\n" +
	"\x0eRecvPlatFormID\x18\x03 \x01(\x05R\x0eRecvPlatFormID\"3\n" +
	"\x17GetUsersOnlineStatusReq\x12\x18\n" +
	"\auserIDs\x18\x01 \x03(\tR\auserIDs\"\xb6\x04\n" +
	"\x18GetUsersOnlineStatusResp\x12_\n" +
	"\rsuccessResult\x18\x01 \x03(\v29.openim.msggateway.GetUsersOnlineStatusResp.SuccessResultR\rsuccessResult\x12\\\n" +
	"\ffailedResult\x18\x02 \x03(\v28.openim.msggateway.GetUsersOnlineStatusResp.FailedDetailR\ffailedResult\x1a\x81\x01\n" +
	"\rSuccessDetail\x12\x1e\n" +
	"\n" +
	"platformID\x18\x01 \x01(\x05R\n" +
	"platformID\x12\x16\n" +
	"\x06connID\x18\x02 \x01(\tR\x06connID\x12\"\n" +
	"\fisBackground\x18\x03 \x01(\bR\fisBackground\x12\x14\n" +
	"\x05token\x18\x04 \x01(\tR\x05token\x1a&\n" +
	"\fFailedDetail\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\x1a\xae\x01\n" +
	"\rSuccessResult\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12m\n" +
	"\x14detailPlatformStatus\x18\x03 \x03(\v29.openim.msggateway.GetUsersOnlineStatusResp.SuccessDetailR\x14detailPlatformStatus\"\x98\x01\n" +
	"\fSingleDetail\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12X\n" +
	"\x13singlePlatformToken\x18\x03 \x03(\v2&.openim.msggateway.SinglePlatformTokenR\x13singlePlatformToken\"a\n" +
	"\x13SinglePlatformToken\x12\x1e\n" +
	"\n" +
	"platformID\x18\x01 \x01(\x05R\n" +
	"platformID\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x14\n" +
	"\x05token\x18\x03 \x03(\tR\x05token\"\\\n" +
	"\x12KickUserOfflineReq\x12\x1e\n" +
	"\n" +
	"platformID\x18\x01 \x01(\x05R\n" +
	"platformID\x12&\n" +
	"\x0ekickUserIDList\x18\x02 \x03(\tR\x0ekickUserIDList\"\x15\n" +
	"\x13KickUserOfflineResp\"j\n" +
	"\x1aMultiTerminalLoginCheckReq\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\x12\x1e\n" +
	"\n" +
	"platformID\x18\x02 \x01(\x05R\n" +
	"platformID\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\"\x1d\n" +
	"\x1bMultiTerminalLoginCheckResp2\xa7\x05\n" +
	"\n" +
	"msgGateway\x12Z\n" +
	"\rOnlinePushMsg\x12#.openim.msggateway.OnlinePushMsgReq\x1a$.openim.msggateway.OnlinePushMsgResp\x12o\n" +
	"\x14GetUsersOnlineStatus\x12*.openim.msggateway.GetUsersOnlineStatusReq\x1a+.openim.msggateway.GetUsersOnlineStatusResp\x12r\n" +
	"\x15OnlineBatchPushOneMsg\x12+.openim.msggateway.OnlineBatchPushOneMsgReq\x1a,.openim.msggateway.OnlineBatchPushOneMsgResp\x12|\n" +
	"\x1fSuperGroupOnlineBatchPushOneMsg\x12+.openim.msggateway.OnlineBatchPushOneMsgReq\x1a,.openim.msggateway.OnlineBatchPushOneMsgResp\x12`\n" +
	"\x0fKickUserOffline\x12%.openim.msggateway.KickUserOfflineReq\x1a&.openim.msggateway.KickUserOfflineResp\x12x\n" +
	"\x17MultiTerminalLoginCheck\x12-.openim.msggateway.MultiTerminalLoginCheckReq\x1a..openim.msggateway.MultiTerminalLoginCheckRespB*Z(github.com/openimsdk/protocol/msggatewayb\x06proto3"

var (
	file_msggateway_msggateway_proto_rawDescOnce sync.Once
	file_msggateway_msggateway_proto_rawDescData []byte
)

func file_msggateway_msggateway_proto_rawDescGZIP() []byte {
	file_msggateway_msggateway_proto_rawDescOnce.Do(func() {
		file_msggateway_msggateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_msggateway_msggateway_proto_rawDesc), len(file_msggateway_msggateway_proto_rawDesc)))
	})
	return file_msggateway_msggateway_proto_rawDescData
}

var file_msggateway_msggateway_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_msggateway_msggateway_proto_goTypes = []any{
	(*OnlinePushMsgReq)(nil),                       // 0: openim.msggateway.OnlinePushMsgReq
	(*OnlinePushMsgResp)(nil),                      // 1: openim.msggateway.OnlinePushMsgResp
	(*SingleMsgToUserResults)(nil),                 // 2: openim.msggateway.SingleMsgToUserResults
	(*OnlineBatchPushOneMsgReq)(nil),               // 3: openim.msggateway.OnlineBatchPushOneMsgReq
	(*OnlineBatchPushOneMsgResp)(nil),              // 4: openim.msggateway.OnlineBatchPushOneMsgResp
	(*SingleMsgToUserPlatform)(nil),                // 5: openim.msggateway.SingleMsgToUserPlatform
	(*GetUsersOnlineStatusReq)(nil),                // 6: openim.msggateway.GetUsersOnlineStatusReq
	(*GetUsersOnlineStatusResp)(nil),               // 7: openim.msggateway.GetUsersOnlineStatusResp
	(*SingleDetail)(nil),                           // 8: openim.msggateway.SingleDetail
	(*SinglePlatformToken)(nil),                    // 9: openim.msggateway.SinglePlatformToken
	(*KickUserOfflineReq)(nil),                     // 10: openim.msggateway.KickUserOfflineReq
	(*KickUserOfflineResp)(nil),                    // 11: openim.msggateway.KickUserOfflineResp
	(*MultiTerminalLoginCheckReq)(nil),             // 12: openim.msggateway.MultiTerminalLoginCheckReq
	(*MultiTerminalLoginCheckResp)(nil),            // 13: openim.msggateway.MultiTerminalLoginCheckResp
	(*GetUsersOnlineStatusResp_SuccessDetail)(nil), // 14: openim.msggateway.GetUsersOnlineStatusResp.SuccessDetail
	(*GetUsersOnlineStatusResp_FailedDetail)(nil),  // 15: openim.msggateway.GetUsersOnlineStatusResp.FailedDetail
	(*GetUsersOnlineStatusResp_SuccessResult)(nil), // 16: openim.msggateway.GetUsersOnlineStatusResp.SuccessResult
	(*sdkws.MsgData)(nil),                          // 17: openim.sdkws.MsgData
}
var file_msggateway_msggateway_proto_depIdxs = []int32{
	17, // 0: openim.msggateway.OnlinePushMsgReq.msgData:type_name -> openim.sdkws.MsgData
	5,  // 1: openim.msggateway.OnlinePushMsgResp.resp:type_name -> openim.msggateway.SingleMsgToUserPlatform
	5,  // 2: openim.msggateway.SingleMsgToUserResults.resp:type_name -> openim.msggateway.SingleMsgToUserPlatform
	17, // 3: openim.msggateway.OnlineBatchPushOneMsgReq.msgData:type_name -> openim.sdkws.MsgData
	2,  // 4: openim.msggateway.OnlineBatchPushOneMsgResp.singlePushResult:type_name -> openim.msggateway.SingleMsgToUserResults
	16, // 5: openim.msggateway.GetUsersOnlineStatusResp.successResult:type_name -> openim.msggateway.GetUsersOnlineStatusResp.SuccessResult
	15, // 6: openim.msggateway.GetUsersOnlineStatusResp.failedResult:type_name -> openim.msggateway.GetUsersOnlineStatusResp.FailedDetail
	9,  // 7: openim.msggateway.SingleDetail.singlePlatformToken:type_name -> openim.msggateway.SinglePlatformToken
	14, // 8: openim.msggateway.GetUsersOnlineStatusResp.SuccessResult.detailPlatformStatus:type_name -> openim.msggateway.GetUsersOnlineStatusResp.SuccessDetail
	0,  // 9: openim.msggateway.msgGateway.OnlinePushMsg:input_type -> openim.msggateway.OnlinePushMsgReq
	6,  // 10: openim.msggateway.msgGateway.GetUsersOnlineStatus:input_type -> openim.msggateway.GetUsersOnlineStatusReq
	3,  // 11: openim.msggateway.msgGateway.OnlineBatchPushOneMsg:input_type -> openim.msggateway.OnlineBatchPushOneMsgReq
	3,  // 12: openim.msggateway.msgGateway.SuperGroupOnlineBatchPushOneMsg:input_type -> openim.msggateway.OnlineBatchPushOneMsgReq
	10, // 13: openim.msggateway.msgGateway.KickUserOffline:input_type -> openim.msggateway.KickUserOfflineReq
	12, // 14: openim.msggateway.msgGateway.MultiTerminalLoginCheck:input_type -> openim.msggateway.MultiTerminalLoginCheckReq
	1,  // 15: openim.msggateway.msgGateway.OnlinePushMsg:output_type -> openim.msggateway.OnlinePushMsgResp
	7,  // 16: openim.msggateway.msgGateway.GetUsersOnlineStatus:output_type -> openim.msggateway.GetUsersOnlineStatusResp
	4,  // 17: openim.msggateway.msgGateway.OnlineBatchPushOneMsg:output_type -> openim.msggateway.OnlineBatchPushOneMsgResp
	4,  // 18: openim.msggateway.msgGateway.SuperGroupOnlineBatchPushOneMsg:output_type -> openim.msggateway.OnlineBatchPushOneMsgResp
	11, // 19: openim.msggateway.msgGateway.KickUserOffline:output_type -> openim.msggateway.KickUserOfflineResp
	13, // 20: openim.msggateway.msgGateway.MultiTerminalLoginCheck:output_type -> openim.msggateway.MultiTerminalLoginCheckResp
	15, // [15:21] is the sub-list for method output_type
	9,  // [9:15] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_msggateway_msggateway_proto_init() }
func file_msggateway_msggateway_proto_init() {
	if File_msggateway_msggateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_msggateway_msggateway_proto_rawDesc), len(file_msggateway_msggateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_msggateway_msggateway_proto_goTypes,
		DependencyIndexes: file_msggateway_msggateway_proto_depIdxs,
		MessageInfos:      file_msggateway_msggateway_proto_msgTypes,
	}.Build()
	File_msggateway_msggateway_proto = out.File
	file_msggateway_msggateway_proto_goTypes = nil
	file_msggateway_msggateway_proto_depIdxs = nil
}
