// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: statistics/statistics.proto

package statistics

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_statistics_statistics_proto protoreflect.FileDescriptor

const file_statistics_statistics_proto_rawDesc = "" +
	"\n" +
	"\x1bstatistics/statistics.proto\x12\x11openim.statisticsB*Z(github.com/openimsdk/protocol/statisticsb\x06proto3"

var file_statistics_statistics_proto_goTypes = []any{}
var file_statistics_statistics_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_statistics_statistics_proto_init() }
func file_statistics_statistics_proto_init() {
	if File_statistics_statistics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_statistics_statistics_proto_rawDesc), len(file_statistics_statistics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_statistics_statistics_proto_goTypes,
		DependencyIndexes: file_statistics_statistics_proto_depIdxs,
	}.Build()
	File_statistics_statistics_proto = out.File
	file_statistics_statistics_proto_goTypes = nil
	file_statistics_statistics_proto_depIdxs = nil
}
