// Copyright © 2023 OpenIM. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: third/third.proto

package third

import (
	sdkws "github.com/openimsdk/protocol/sdkws"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KeyValues struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key"`
	Values        []string               `protobuf:"bytes,2,rep,name=values,proto3" json:"values"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValues) Reset() {
	*x = KeyValues{}
	mi := &file_third_third_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValues) ProtoMessage() {}

func (x *KeyValues) ProtoReflect() protoreflect.Message {
	mi := &file_third_third_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValues.ProtoReflect.Descriptor instead.
func (*KeyValues) Descriptor() ([]byte, []int) {
	return file_third_third_proto_rawDescGZIP(), []int{0}
}

func (x *KeyValues) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyValues) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type SignPart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartNumber    int32                  `protobuf:"varint,1,opt,name=partNumber,proto3" json:"partNumber"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url"`
	Query         []*KeyValues           `protobuf:"bytes,3,rep,name=query,proto3" json:"query"`
	Header        []*KeyValues           `protobuf:"bytes,4,rep,name=header,proto3" json:"header"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignPart) Reset() {
	*x = SignPart{}
	mi := &file_third_third_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignPart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignPart) ProtoMessage() {}

func (x *SignPart) ProtoReflect() protoreflect.Message {
	mi := &file_third_third_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignPart.ProtoReflect.Descriptor instead.
func (*SignPart) Descriptor() ([]byte, []int) {
	return file_third_third_proto_rawDescGZIP(), []int{1}
}

func (x *SignPart) GetPartNumber() int32 {
	if x != nil {
		return x.PartNumber
	}
	return 0
}

func (x *SignPart) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *SignPart) GetQuery() []*KeyValues {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *SignPart) GetHeader() []*KeyValues {
	if x != nil {
		return x.Header
	}
	return nil
}

type AuthSignParts struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url"`
	Query         []*KeyValues           `protobuf:"bytes,2,rep,name=query,proto3" json:"query"`
	Header        []*KeyValues           `protobuf:"bytes,3,rep,name=header,proto3" json:"header"`
	Parts         []*SignPart            `protobuf:"bytes,4,rep,name=parts,proto3" json:"parts"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthSignParts) Reset() {
	*x = AuthSignParts{}
	mi := &file_third_third_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthSignParts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthSignParts) ProtoMessage() {}

func (x *AuthSignParts) ProtoReflect() protoreflect.Message {
	mi := &file_third_third_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthSignParts.ProtoReflect.Descriptor instead.
func (*AuthSignParts) Descriptor() ([]byte, []int) {
	return file_third_third_proto_rawDescGZIP(), []int{2}
}

func (x *AuthSignParts) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *AuthSignParts) GetQuery() []*KeyValues {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *AuthSignParts) GetHeader() []*KeyValues {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *AuthSignParts) GetParts() []*SignPart {
	if x != nil {
		return x.Parts
	}
	return nil
}

type PartLimitReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartLimitReq) Reset() {
	*x = PartLimitReq{}
	mi := &file_third_third_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartLimitReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartLimitReq) ProtoMessage() {}

func (x *PartLimitReq) ProtoReflect() protoreflect.Message {
	mi := &file_third_third_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartLimitReq.ProtoReflect.Descriptor instead.
func (*PartLimitReq) Descriptor() ([]byte, []int) {
	return file_third_third_proto_rawDescGZIP(), []int{3}
}

type PartLimitResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MinPartSize   int64                  `protobuf:"varint,1,opt,name=minPartSize,proto3" json:"minPartSize"`
	MaxPartSize   int64                  `protobuf:"varint,2,opt,name=maxPartSize,proto3" json:"maxPartSize"`
	MaxNumSize    int32                  `protobuf:"varint,3,opt,name=maxNumSize,proto3" json:"maxNumSize"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartLimitResp) Reset() {
	*x = PartLimitResp{}
	mi := &file_third_third_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartLimitResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartLimitResp) ProtoMessage() {}

func (x *PartLimitResp) ProtoReflect() protoreflect.Message {
	mi := &file_third_third_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartLimitResp.ProtoReflect.Descriptor instead.
func (*PartLimitResp) Descriptor() ([]byte, []int) {
	return file_third_third_proto_rawDescGZIP(), []int{4}
}

func (x *PartLimitResp) GetMinPartSize() int64 {
	if x != nil {
		return x.MinPartSize
	}
	return 0
}

func (x *PartLimitResp) GetMaxPartSize() int64 {
	if x != nil {
		return x.MaxPartSize
	}
	return 0
}

func (x *PartLimitResp) GetMaxNumSize() int32 {
	if x != nil {
		return x.MaxNumSize
	}
	return 0
}

type PartSizeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          int64                  `protobuf:"varint,1,opt,name=size,proto3" json:"size"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartSizeReq) Reset() {
	*x = PartSizeReq{}
	mi := &file_third_third_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartSizeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartSizeReq) ProtoMessage() {}

func (x *PartSizeReq) ProtoReflect() protoreflect.Message {
	mi := &file_third_third_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartSizeReq.ProtoReflect.Descriptor instead.
func (*PartSizeReq) Descriptor() ([]byte, []int) {
	return file_third_third_proto_rawDescGZIP(), []int{5}
}

func (x *PartSizeReq) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type PartSizeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartSizeResp) Reset() {
	*x = PartSizeResp{}
	mi := &file_third_third_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartSizeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartSizeResp) ProtoMessage() {}

func (x *PartSizeResp) ProtoReflect() protoreflect.Message {
	mi := &file_third_third_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartSizeResp.ProtoReflect.Descriptor instead.
func (*PartSizeResp) Descriptor() ([]byte, []int) {
	return file_third_third_proto_rawDescGZIP(), []int{6}
}

func (x *PartSizeResp) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type InitiateMultipartUploadReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size"`
	PartSize      int64                  `protobuf:"varint,3,opt,name=partSize,proto3" json:"partSize"`
	MaxParts      int32                  `protobuf:"varint,4,opt,name=maxParts,proto3" json:"maxParts"`
	Cause         string                 `protobuf:"bytes,5,opt,name=cause,proto3" json:"cause"`
	Name          string                 `protobuf:"bytes,6,opt,name=name,proto3" json:"name"`
	ContentType   string                 `protobuf:"bytes,7,opt,name=contentType,proto3" json:"contentType"`
	UrlPrefix     string                 `protobuf:"bytes,8,opt,name=urlPrefix,proto3" json:"urlPrefix"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitiateMultipartUploadReq) Reset() {
	*x = InitiateMultipartUploadReq{}
	mi := &file_third_third_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateMultipartUploadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateMultipartUploadReq) ProtoMessage() {}

func (x *InitiateMultipartUploadReq) ProtoReflect() protoreflect.Message {
	mi := &file_third_third_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateMultipartUploadReq.ProtoReflect.Descriptor instead.
func (*InitiateMultipartUploadReq) Descriptor() ([]byte, []int) {
	return file_third_third_proto_rawDescGZIP(), []int{7}
}

func (x *InitiateMultipartUploadReq) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *InitiateMultipartUploadReq) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *InitiateMultipartUploadReq) GetPartSize() int64 {
	if x != nil {
		return x.PartSize
	}
	return 0
}

func (x *InitiateMultipartUploadReq) GetMaxParts() int32 {
	if x != nil {
		return x.MaxParts
	}
	return 0
}

func (x *InitiateMultipartUploadReq) GetCause() string {
	if x != nil {
		return x.Cause
	}
	return ""
}

func (x *InitiateMultipartUploadReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InitiateMultipartUploadReq) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *InitiateMultipartUploadReq) GetUrlPrefix() string {
	if x != nil {
		return x.UrlPrefix
	}
	return ""
}

type UploadInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadID      string                 `protobuf:"bytes,1,opt,name=uploadID,proto3" json:"uploadID"`
	PartSize      int64                  `protobuf:"varint,2,opt,name=partSize,proto3" json:"partSize"`
	Sign          *AuthSignParts         `protobuf:"bytes,3,opt,name=sign,proto3" json:"sign"`
	ExpireTime    int64                  `protobuf:"varint,4,opt,name=expireTime,proto3" json:"expireTime"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadInfo) Reset() {
	*x = UploadInfo{}
	mi := &file_third_third_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadInfo) ProtoMessage() {}

func (x *UploadInfo) ProtoReflect() protoreflect.Message {
	mi := &file_third_third_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadInfo.ProtoReflect.Descriptor instead.
func (*UploadInfo) Descriptor() ([]byte, []int) {
	return file_third_third_proto_rawDescGZIP(), []int{8}
}

func (x *UploadInfo) GetUploadID() string {
	if x != nil {
		return x.UploadID
	}
	return ""
}

func (x *UploadInfo) GetPartSize() int64 {
	if x != nil {
		return x.PartSize
	}
	return 0
}

func (x *UploadInfo) GetSign() *AuthSignParts {
	if x != nil {
		return x.Sign
	}
	return nil
}

func (x *UploadInfo) GetExpireTime() int64 {
	if x != nil {
		return x.ExpireTime
	}
	return 0
}

type InitiateMultipartUploadResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url"`
	Upload        *UploadInfo            `protobuf:"bytes,2,opt,name=upload,proto3" json:"upload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitiateMultipartUploadResp) Reset() {
	*x = InitiateMultipartUploadResp{}
	mi := &file_third_third_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateMultipartUploadResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateMultipartUploadResp) ProtoMessage() {}

func (x *InitiateMultipartUploadResp) ProtoReflect() protoreflect.Message {
	mi := &file_third_third_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateMultipartUploadResp.ProtoReflect.Descriptor instead.
func (*InitiateMultipartUploadResp) Descriptor() ([]byte, []int) {
	return file_third_third_proto_rawDescGZIP(), []int{9}
}

func (x *InitiateMultipartUploadResp) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *InitiateMultipartUploadResp) GetUpload() *UploadInfo {
	if x != nil {
		return x.Upload
	}
	return nil
}

type AuthSignReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadID      string                 `protobuf:"bytes,1,opt,name=uploadID,proto3" json:"uploadID"`
	PartNumbers   []int32                `protobuf:"varint,2,rep,packed,name=partNumbers,proto3" json:"partNumbers"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthSignReq) Reset() {
	*x = AuthSignReq{}
	mi := &file_third_third_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthSignReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthSignReq) ProtoMessage() {}

func (x *AuthSignReq) ProtoReflect() protoreflect.Message {
	mi := &file_third_third_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthSignReq.ProtoReflect.Descriptor instead.
func (*AuthSignReq) Descriptor() ([]byte, []int) {
	return file_third_third_proto_rawDescGZIP(), []int{10}
}

func (x *AuthSignReq) GetUploadID() string {
	if x != nil {
		return x.UploadID
	}
	return ""
}

func (x *AuthSignReq) GetPartNumbers() []int32 {
	if x != nil {
		return x.PartNumbers
	}
	return nil
}

type AuthSignResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url"`
	Query         []*KeyValues           `protobuf:"bytes,2,rep,name=query,proto3" json:"query"`
	Header        []*KeyValues           `protobuf:"bytes,3,rep,name=header,proto3" json:"header"`
	Parts         []*SignPart            `protobuf:"bytes,4,rep,name=parts,proto3" json:"parts"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthSignResp) Reset() {
	*x = AuthSignResp{}
	mi := &file_third_third_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthSignResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthSignResp) ProtoMessage() {}

func (x *AuthSignResp) ProtoReflect() protoreflect.Message {
	mi := &file_third_third_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthSignResp.ProtoReflect.Descriptor instead.
func (*AuthSignResp) Descriptor() ([]byte, []int) {
	return file_third_third_proto_rawDescGZIP(), []int{11}
}

func (x *AuthSignResp) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *AuthSignResp) GetQuery() []*KeyValues {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *AuthSignResp) GetHeader() []*KeyValues {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *AuthSignResp) GetParts() []*SignPart {
	if x != nil {
		return x.Parts
	}
	return nil
}

type CompleteMultipartUploadReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploadID      string                 `protobuf:"bytes,1,opt,name=uploadID,proto3" json:"uploadID"`
	Parts         []string               `protobuf:"bytes,2,rep,name=parts,proto3" json:"parts"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name"`
	ContentType   string                 `protobuf:"bytes,4,opt,name=contentType,proto3" json:"contentType"`
	Cause         string                 `protobuf:"bytes,5,opt,name=cause,proto3" json:"cause"`
	UrlPrefix     string                 `protobuf:"bytes,6,opt,name=urlPrefix,proto3" json:"urlPrefix"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteMultipartUploadReq) Reset() {
	*x = CompleteMultipartUploadReq{}
	mi := &file_third_third_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteMultipartUploadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteMultipartUploadReq) ProtoMessage() {}

func (x *CompleteMultipartUploadReq) ProtoReflect() protoreflect.Message {
	mi := &file_third_third_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteMultipartUploadReq.ProtoReflect.Descriptor instead.
func (*CompleteMultipartUploadReq) Descriptor() ([]byte, []int) {
	return file_third_third_proto_rawDescGZIP(), []int{12}
}

func (x *CompleteMultipartUploadReq) GetUploadID() string {
	if x != nil {
		return x.UploadID
	}
	return ""
}

func (x *CompleteMultipartUploadReq) GetParts() []string {
	if x != nil {
		return x.Parts
	}
	return nil
}

func (x *CompleteMultipartUploadReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CompleteMultipartUploadReq) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *CompleteMultipartUploadReq) GetCause() string {
	if x != nil {
		return x.Cause
	}
	return ""
}

func (x *CompleteMultipartUploadReq) GetUrlPrefix() string {
	if x != nil {
		return x.UrlPrefix
	}
	return ""
}

type CompleteMultipartUploadResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteMultipartUploadResp) Reset() {
	*x = CompleteMultipartUploadResp{}
	mi := &file_third_third_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteMultipartUploadResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteMultipartUploadResp) ProtoMessage() {}

func (x *CompleteMultipartUploadResp) ProtoReflect() protoreflect.Message {
	mi := &file_third_third_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteMultipartUploadResp.ProtoReflect.Descriptor instead.
func (*CompleteMultipartUploadResp) Descriptor() ([]byte, []int) {
	return file_third_third_proto_rawDescGZIP(), []int{13}
}

func (x *CompleteMultipartUploadResp) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type AccessURLReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name"`
	Query         map[string]string      `protobuf:"bytes,2,rep,name=query,proto3" json:"query" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessURLReq) Reset() {
	*x = AccessURLReq{}
	mi := &file_third_third_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessURLReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessURLReq) ProtoMessage() {}

func (x *AccessURLReq) ProtoReflect() protoreflect.Message {
	mi := &file_third_third_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessURLReq.ProtoReflect.Descriptor instead.
func (*AccessURLReq) Descriptor() ([]byte, []int) {
	return file_third_third_proto_rawDescGZIP(), []int{14}
}

func (x *AccessURLReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AccessURLReq) GetQuery() map[string]string {
	if x != nil {
		return x.Query
	}
	return nil
}

type AccessURLResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url"`
	ExpireTime    int64                  `protobuf:"varint,2,opt,name=expireTime,proto3" json:"expireTime"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessURLResp) Reset() {
	*x = AccessURLResp{}
	mi := &file_third_third_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessURLResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessURLResp) ProtoMessage() {}

func (x *AccessURLResp) ProtoReflect() protoreflect.Message {
	mi := &file_third_third_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessURLResp.ProtoReflect.Descriptor instead.
func (*AccessURLResp) Descriptor() ([]byte, []int) {
	return file_third_third_proto_rawDescGZIP(), []int{15}
}

func (x *AccessURLResp) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *AccessURLResp) GetExpireTime() int64 {
	if x != nil {
		return x.ExpireTime
	}
	return 0
}

type InitiateFormDataReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=contentType,proto3" json:"contentType"`
	Group         string                 `protobuf:"bytes,4,opt,name=group,proto3" json:"group"`
	Millisecond   int64                  `protobuf:"varint,5,opt,name=millisecond,proto3" json:"millisecond"`
	Absolute      bool                   `protobuf:"varint,6,opt,name=absolute,proto3" json:"absolute"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitiateFormDataReq) Reset() {
	*x = InitiateFormDataReq{}
	mi := &file_third_third_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateFormDataReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateFormDataReq) ProtoMessage() {}

func (x *InitiateFormDataReq) ProtoReflect() protoreflect.Message {
	mi := &file_third_third_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateFormDataReq.ProtoReflect.Descriptor instead.
func (*InitiateFormDataReq) Descriptor() ([]byte, []int) {
	return file_third_third_proto_rawDescGZIP(), []int{16}
}

func (x *InitiateFormDataReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InitiateFormDataReq) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *InitiateFormDataReq) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *InitiateFormDataReq) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *InitiateFormDataReq) GetMillisecond() int64 {
	if x != nil {
		return x.Millisecond
	}
	return 0
}

func (x *InitiateFormDataReq) GetAbsolute() bool {
	if x != nil {
		return x.Absolute
	}
	return false
}

type InitiateFormDataResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url"`
	File          string                 `protobuf:"bytes,3,opt,name=file,proto3" json:"file"`
	Header        []*KeyValues           `protobuf:"bytes,4,rep,name=header,proto3" json:"header"`
	FormData      map[string]string      `protobuf:"bytes,5,rep,name=formData,proto3" json:"formData" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Expires       int64                  `protobuf:"varint,6,opt,name=expires,proto3" json:"expires"`
	SuccessCodes  []int32                `protobuf:"varint,7,rep,packed,name=successCodes,proto3" json:"successCodes"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitiateFormDataResp) Reset() {
	*x = InitiateFormDataResp{}
	mi := &file_third_third_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateFormDataResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateFormDataResp) ProtoMessage() {}

func (x *InitiateFormDataResp) ProtoReflect() protoreflect.Message {
	mi := &file_third_third_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateFormDataResp.ProtoReflect.Descriptor instead.
func (*InitiateFormDataResp) Descriptor() ([]byte, []int) {
	return file_third_third_proto_rawDescGZIP(), []int{17}
}

func (x *InitiateFormDataResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InitiateFormDataResp) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *InitiateFormDataResp) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *InitiateFormDataResp) GetHeader() []*KeyValues {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *InitiateFormDataResp) GetFormData() map[string]string {
	if x != nil {
		return x.FormData
	}
	return nil
}

func (x *InitiateFormDataResp) GetExpires() int64 {
	if x != nil {
		return x.Expires
	}
	return 0
}

func (x *InitiateFormDataResp) GetSuccessCodes() []int32 {
	if x != nil {
		return x.SuccessCodes
	}
	return nil
}

type CompleteFormDataReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	UrlPrefix     string                 `protobuf:"bytes,2,opt,name=urlPrefix,proto3" json:"urlPrefix"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteFormDataReq) Reset() {
	*x = CompleteFormDataReq{}
	mi := &file_third_third_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteFormDataReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteFormDataReq) ProtoMessage() {}

func (x *CompleteFormDataReq) ProtoReflect() protoreflect.Message {
	mi := &file_third_third_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteFormDataReq.ProtoReflect.Descriptor instead.
func (*CompleteFormDataReq) Descriptor() ([]byte, []int) {
	return file_third_third_proto_rawDescGZIP(), []int{18}
}

func (x *CompleteFormDataReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CompleteFormDataReq) GetUrlPrefix() string {
	if x != nil {
		return x.UrlPrefix
	}
	return ""
}

type CompleteFormDataResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteFormDataResp) Reset() {
	*x = CompleteFormDataResp{}
	mi := &file_third_third_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteFormDataResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteFormDataResp) ProtoMessage() {}

func (x *CompleteFormDataResp) ProtoReflect() protoreflect.Message {
	mi := &file_third_third_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteFormDataResp.ProtoReflect.Descriptor instead.
func (*CompleteFormDataResp) Descriptor() ([]byte, []int) {
	return file_third_third_proto_rawDescGZIP(), []int{19}
}

func (x *CompleteFormDataResp) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type DeleteOutdatedDataReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExpireTime    int64                  `protobuf:"varint,1,opt,name=expireTime,proto3" json:"expireTime"`
	ObjectGroup   []string               `protobuf:"bytes,2,rep,name=objectGroup,proto3" json:"objectGroup"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOutdatedDataReq) Reset() {
	*x = DeleteOutdatedDataReq{}
	mi := &file_third_third_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOutdatedDataReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOutdatedDataReq) ProtoMessage() {}

func (x *DeleteOutdatedDataReq) ProtoReflect() protoreflect.Message {
	mi := &file_third_third_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOutdatedDataReq.ProtoReflect.Descriptor instead.
func (*DeleteOutdatedDataReq) Descriptor() ([]byte, []int) {
	return file_third_third_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteOutdatedDataReq) GetExpireTime() int64 {
	if x != nil {
		return x.ExpireTime
	}
	return 0
}

func (x *DeleteOutdatedDataReq) GetObjectGroup() []string {
	if x != nil {
		return x.ObjectGroup
	}
	return nil
}

func (x *DeleteOutdatedDataReq) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type DeleteOutdatedDataResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOutdatedDataResp) Reset() {
	*x = DeleteOutdatedDataResp{}
	mi := &file_third_third_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOutdatedDataResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOutdatedDataResp) ProtoMessage() {}

func (x *DeleteOutdatedDataResp) ProtoReflect() protoreflect.Message {
	mi := &file_third_third_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOutdatedDataResp.ProtoReflect.Descriptor instead.
func (*DeleteOutdatedDataResp) Descriptor() ([]byte, []int) {
	return file_third_third_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteOutdatedDataResp) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type FcmUpdateTokenReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlatformID    int32                  `protobuf:"varint,1,opt,name=platformID,proto3" json:"platformID"`
	FcmToken      string                 `protobuf:"bytes,2,opt,name=fcmToken,proto3" json:"fcmToken"`
	Account       string                 `protobuf:"bytes,3,opt,name=account,proto3" json:"account"`
	ExpireTime    int64                  `protobuf:"varint,4,opt,name=expireTime,proto3" json:"expireTime"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FcmUpdateTokenReq) Reset() {
	*x = FcmUpdateTokenReq{}
	mi := &file_third_third_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FcmUpdateTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FcmUpdateTokenReq) ProtoMessage() {}

func (x *FcmUpdateTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_third_third_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FcmUpdateTokenReq.ProtoReflect.Descriptor instead.
func (*FcmUpdateTokenReq) Descriptor() ([]byte, []int) {
	return file_third_third_proto_rawDescGZIP(), []int{22}
}

func (x *FcmUpdateTokenReq) GetPlatformID() int32 {
	if x != nil {
		return x.PlatformID
	}
	return 0
}

func (x *FcmUpdateTokenReq) GetFcmToken() string {
	if x != nil {
		return x.FcmToken
	}
	return ""
}

func (x *FcmUpdateTokenReq) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *FcmUpdateTokenReq) GetExpireTime() int64 {
	if x != nil {
		return x.ExpireTime
	}
	return 0
}

type FcmUpdateTokenResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FcmUpdateTokenResp) Reset() {
	*x = FcmUpdateTokenResp{}
	mi := &file_third_third_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FcmUpdateTokenResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FcmUpdateTokenResp) ProtoMessage() {}

func (x *FcmUpdateTokenResp) ProtoReflect() protoreflect.Message {
	mi := &file_third_third_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FcmUpdateTokenResp.ProtoReflect.Descriptor instead.
func (*FcmUpdateTokenResp) Descriptor() ([]byte, []int) {
	return file_third_third_proto_rawDescGZIP(), []int{23}
}

type SetAppBadgeReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserID         string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID"`
	AppUnreadCount int32                  `protobuf:"varint,2,opt,name=appUnreadCount,proto3" json:"appUnreadCount"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SetAppBadgeReq) Reset() {
	*x = SetAppBadgeReq{}
	mi := &file_third_third_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAppBadgeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAppBadgeReq) ProtoMessage() {}

func (x *SetAppBadgeReq) ProtoReflect() protoreflect.Message {
	mi := &file_third_third_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAppBadgeReq.ProtoReflect.Descriptor instead.
func (*SetAppBadgeReq) Descriptor() ([]byte, []int) {
	return file_third_third_proto_rawDescGZIP(), []int{24}
}

func (x *SetAppBadgeReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *SetAppBadgeReq) GetAppUnreadCount() int32 {
	if x != nil {
		return x.AppUnreadCount
	}
	return 0
}

type SetAppBadgeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAppBadgeResp) Reset() {
	*x = SetAppBadgeResp{}
	mi := &file_third_third_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAppBadgeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAppBadgeResp) ProtoMessage() {}

func (x *SetAppBadgeResp) ProtoReflect() protoreflect.Message {
	mi := &file_third_third_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAppBadgeResp.ProtoReflect.Descriptor instead.
func (*SetAppBadgeResp) Descriptor() ([]byte, []int) {
	return file_third_third_proto_rawDescGZIP(), []int{25}
}

type FileURL struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename"`
	URL           string                 `protobuf:"bytes,2,opt,name=URL,proto3" json:"URL"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileURL) Reset() {
	*x = FileURL{}
	mi := &file_third_third_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileURL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileURL) ProtoMessage() {}

func (x *FileURL) ProtoReflect() protoreflect.Message {
	mi := &file_third_third_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileURL.ProtoReflect.Descriptor instead.
func (*FileURL) Descriptor() ([]byte, []int) {
	return file_third_third_proto_rawDescGZIP(), []int{26}
}

func (x *FileURL) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FileURL) GetURL() string {
	if x != nil {
		return x.URL
	}
	return ""
}

type UploadLogsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      int32                  `protobuf:"varint,1,opt,name=platform,proto3" json:"platform"`
	FileURLs      []*FileURL             `protobuf:"bytes,2,rep,name=fileURLs,proto3" json:"fileURLs"`
	AppFramework  string                 `protobuf:"bytes,3,opt,name=appFramework,proto3" json:"appFramework"`
	Version       string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version"`
	Ex            string                 `protobuf:"bytes,4,opt,name=ex,proto3" json:"ex"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadLogsReq) Reset() {
	*x = UploadLogsReq{}
	mi := &file_third_third_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadLogsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadLogsReq) ProtoMessage() {}

func (x *UploadLogsReq) ProtoReflect() protoreflect.Message {
	mi := &file_third_third_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadLogsReq.ProtoReflect.Descriptor instead.
func (*UploadLogsReq) Descriptor() ([]byte, []int) {
	return file_third_third_proto_rawDescGZIP(), []int{27}
}

func (x *UploadLogsReq) GetPlatform() int32 {
	if x != nil {
		return x.Platform
	}
	return 0
}

func (x *UploadLogsReq) GetFileURLs() []*FileURL {
	if x != nil {
		return x.FileURLs
	}
	return nil
}

func (x *UploadLogsReq) GetAppFramework() string {
	if x != nil {
		return x.AppFramework
	}
	return ""
}

func (x *UploadLogsReq) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *UploadLogsReq) GetEx() string {
	if x != nil {
		return x.Ex
	}
	return ""
}

type UploadLogsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadLogsResp) Reset() {
	*x = UploadLogsResp{}
	mi := &file_third_third_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadLogsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadLogsResp) ProtoMessage() {}

func (x *UploadLogsResp) ProtoReflect() protoreflect.Message {
	mi := &file_third_third_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadLogsResp.ProtoReflect.Descriptor instead.
func (*UploadLogsResp) Descriptor() ([]byte, []int) {
	return file_third_third_proto_rawDescGZIP(), []int{28}
}

type DeleteLogsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LogIDs        []string               `protobuf:"bytes,1,rep,name=logIDs,proto3" json:"logIDs"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLogsReq) Reset() {
	*x = DeleteLogsReq{}
	mi := &file_third_third_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLogsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLogsReq) ProtoMessage() {}

func (x *DeleteLogsReq) ProtoReflect() protoreflect.Message {
	mi := &file_third_third_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLogsReq.ProtoReflect.Descriptor instead.
func (*DeleteLogsReq) Descriptor() ([]byte, []int) {
	return file_third_third_proto_rawDescGZIP(), []int{29}
}

func (x *DeleteLogsReq) GetLogIDs() []string {
	if x != nil {
		return x.LogIDs
	}
	return nil
}

type DeleteLogsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLogsResp) Reset() {
	*x = DeleteLogsResp{}
	mi := &file_third_third_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLogsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLogsResp) ProtoMessage() {}

func (x *DeleteLogsResp) ProtoReflect() protoreflect.Message {
	mi := &file_third_third_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLogsResp.ProtoReflect.Descriptor instead.
func (*DeleteLogsResp) Descriptor() ([]byte, []int) {
	return file_third_third_proto_rawDescGZIP(), []int{30}
}

type SearchLogsReq struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Keyword       string                   `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword"`
	StartTime     int64                    `protobuf:"varint,2,opt,name=startTime,proto3" json:"startTime"`
	EndTime       int64                    `protobuf:"varint,3,opt,name=endTime,proto3" json:"endTime"`
	Pagination    *sdkws.RequestPagination `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchLogsReq) Reset() {
	*x = SearchLogsReq{}
	mi := &file_third_third_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchLogsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchLogsReq) ProtoMessage() {}

func (x *SearchLogsReq) ProtoReflect() protoreflect.Message {
	mi := &file_third_third_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchLogsReq.ProtoReflect.Descriptor instead.
func (*SearchLogsReq) Descriptor() ([]byte, []int) {
	return file_third_third_proto_rawDescGZIP(), []int{31}
}

func (x *SearchLogsReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *SearchLogsReq) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *SearchLogsReq) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *SearchLogsReq) GetPagination() *sdkws.RequestPagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type LogInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID"`
	Platform      string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url"`
	CreateTime    int64                  `protobuf:"varint,4,opt,name=createTime,proto3" json:"createTime"`
	Nickname      string                 `protobuf:"bytes,5,opt,name=nickname,proto3" json:"nickname"`
	LogID         string                 `protobuf:"bytes,6,opt,name=logID,proto3" json:"logID"`
	Filename      string                 `protobuf:"bytes,7,opt,name=filename,proto3" json:"filename"`
	SystemType    string                 `protobuf:"bytes,8,opt,name=systemType,proto3" json:"systemType"`
	Ex            string                 `protobuf:"bytes,9,opt,name=ex,proto3" json:"ex"`
	Version       string                 `protobuf:"bytes,10,opt,name=version,proto3" json:"version"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogInfo) Reset() {
	*x = LogInfo{}
	mi := &file_third_third_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogInfo) ProtoMessage() {}

func (x *LogInfo) ProtoReflect() protoreflect.Message {
	mi := &file_third_third_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogInfo.ProtoReflect.Descriptor instead.
func (*LogInfo) Descriptor() ([]byte, []int) {
	return file_third_third_proto_rawDescGZIP(), []int{32}
}

func (x *LogInfo) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *LogInfo) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *LogInfo) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *LogInfo) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *LogInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *LogInfo) GetLogID() string {
	if x != nil {
		return x.LogID
	}
	return ""
}

func (x *LogInfo) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *LogInfo) GetSystemType() string {
	if x != nil {
		return x.SystemType
	}
	return ""
}

func (x *LogInfo) GetEx() string {
	if x != nil {
		return x.Ex
	}
	return ""
}

func (x *LogInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type SearchLogsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LogsInfos     []*LogInfo             `protobuf:"bytes,1,rep,name=logsInfos,proto3" json:"logsInfos"`
	Total         uint32                 `protobuf:"varint,2,opt,name=total,proto3" json:"total"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchLogsResp) Reset() {
	*x = SearchLogsResp{}
	mi := &file_third_third_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchLogsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchLogsResp) ProtoMessage() {}

func (x *SearchLogsResp) ProtoReflect() protoreflect.Message {
	mi := &file_third_third_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchLogsResp.ProtoReflect.Descriptor instead.
func (*SearchLogsResp) Descriptor() ([]byte, []int) {
	return file_third_third_proto_rawDescGZIP(), []int{33}
}

func (x *SearchLogsResp) GetLogsInfos() []*LogInfo {
	if x != nil {
		return x.LogsInfos
	}
	return nil
}

func (x *SearchLogsResp) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_third_third_proto protoreflect.FileDescriptor

const file_third_third_proto_rawDesc = "" +
	"\n" +
	"\x11third/third.proto\x12\fopenim.third\x1a\x11sdkws/sdkws.proto\"5\n" +
	"\tKeyValues\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x16\n" +
	"\x06values\x18\x02 \x03(\tR\x06values\"\x9c\x01\n" +
	"\bSignPart\x12\x1e\n" +
	"\n" +
	"partNumber\x18\x01 \x01(\x05R\n" +
	"partNumber\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12-\n" +
	"\x05query\x18\x03 \x03(\v2\x17.openim.third.KeyValuesR\x05query\x12/\n" +
	"\x06header\x18\x04 \x03(\v2\x17.openim.third.KeyValuesR\x06header\"\xaf\x01\n" +
	"\rAuthSignParts\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12-\n" +
	"\x05query\x18\x02 \x03(\v2\x17.openim.third.KeyValuesR\x05query\x12/\n" +
	"\x06header\x18\x03 \x03(\v2\x17.openim.third.KeyValuesR\x06header\x12,\n" +
	"\x05parts\x18\x04 \x03(\v2\x16.openim.third.SignPartR\x05parts\"\x0e\n" +
	"\fPartLimitReq\"s\n" +
	"\rPartLimitResp\x12 \n" +
	"\vminPartSize\x18\x01 \x01(\x03R\vminPartSize\x12 \n" +
	"\vmaxPartSize\x18\x02 \x01(\x03R\vmaxPartSize\x12\x1e\n" +
	"\n" +
	"maxNumSize\x18\x03 \x01(\x05R\n" +
	"maxNumSize\"!\n" +
	"\vPartSizeReq\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x03R\x04size\"\"\n" +
	"\fPartSizeResp\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\"\xe6\x01\n" +
	"\x1aInitiateMultipartUploadReq\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x1a\n" +
	"\bpartSize\x18\x03 \x01(\x03R\bpartSize\x12\x1a\n" +
	"\bmaxParts\x18\x04 \x01(\x05R\bmaxParts\x12\x14\n" +
	"\x05cause\x18\x05 \x01(\tR\x05cause\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12 \n" +
	"\vcontentType\x18\a \x01(\tR\vcontentType\x12\x1c\n" +
	"\turlPrefix\x18\b \x01(\tR\turlPrefix\"\x95\x01\n" +
	"\n" +
	"UploadInfo\x12\x1a\n" +
	"\buploadID\x18\x01 \x01(\tR\buploadID\x12\x1a\n" +
	"\bpartSize\x18\x02 \x01(\x03R\bpartSize\x12/\n" +
	"\x04sign\x18\x03 \x01(\v2\x1b.openim.third.AuthSignPartsR\x04sign\x12\x1e\n" +
	"\n" +
	"expireTime\x18\x04 \x01(\x03R\n" +
	"expireTime\"a\n" +
	"\x1bInitiateMultipartUploadResp\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x120\n" +
	"\x06upload\x18\x02 \x01(\v2\x18.openim.third.UploadInfoR\x06upload\"K\n" +
	"\vAuthSignReq\x12\x1a\n" +
	"\buploadID\x18\x01 \x01(\tR\buploadID\x12 \n" +
	"\vpartNumbers\x18\x02 \x03(\x05R\vpartNumbers\"\xae\x01\n" +
	"\fAuthSignResp\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12-\n" +
	"\x05query\x18\x02 \x03(\v2\x17.openim.third.KeyValuesR\x05query\x12/\n" +
	"\x06header\x18\x03 \x03(\v2\x17.openim.third.KeyValuesR\x06header\x12,\n" +
	"\x05parts\x18\x04 \x03(\v2\x16.openim.third.SignPartR\x05parts\"\xb8\x01\n" +
	"\x1aCompleteMultipartUploadReq\x12\x1a\n" +
	"\buploadID\x18\x01 \x01(\tR\buploadID\x12\x14\n" +
	"\x05parts\x18\x02 \x03(\tR\x05parts\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vcontentType\x18\x04 \x01(\tR\vcontentType\x12\x14\n" +
	"\x05cause\x18\x05 \x01(\tR\x05cause\x12\x1c\n" +
	"\turlPrefix\x18\x06 \x01(\tR\turlPrefix\"/\n" +
	"\x1bCompleteMultipartUploadResp\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\x99\x01\n" +
	"\fAccessURLReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12;\n" +
	"\x05query\x18\x02 \x03(\v2%.openim.third.AccessURLReq.QueryEntryR\x05query\x1a8\n" +
	"\n" +
	"QueryEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"A\n" +
	"\rAccessURLResp\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1e\n" +
	"\n" +
	"expireTime\x18\x02 \x01(\x03R\n" +
	"expireTime\"\xb3\x01\n" +
	"\x13InitiateFormDataReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12 \n" +
	"\vcontentType\x18\x03 \x01(\tR\vcontentType\x12\x14\n" +
	"\x05group\x18\x04 \x01(\tR\x05group\x12 \n" +
	"\vmillisecond\x18\x05 \x01(\x03R\vmillisecond\x12\x1a\n" +
	"\babsolute\x18\x06 \x01(\bR\babsolute\"\xc6\x02\n" +
	"\x14InitiateFormDataResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x12\n" +
	"\x04file\x18\x03 \x01(\tR\x04file\x12/\n" +
	"\x06header\x18\x04 \x03(\v2\x17.openim.third.KeyValuesR\x06header\x12L\n" +
	"\bformData\x18\x05 \x03(\v20.openim.third.InitiateFormDataResp.FormDataEntryR\bformData\x12\x18\n" +
	"\aexpires\x18\x06 \x01(\x03R\aexpires\x12\"\n" +
	"\fsuccessCodes\x18\a \x03(\x05R\fsuccessCodes\x1a;\n" +
	"\rFormDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"C\n" +
	"\x13CompleteFormDataReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\turlPrefix\x18\x02 \x01(\tR\turlPrefix\"(\n" +
	"\x14CompleteFormDataResp\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"o\n" +
	"\x15DeleteOutdatedDataReq\x12\x1e\n" +
	"\n" +
	"expireTime\x18\x01 \x01(\x03R\n" +
	"expireTime\x12 \n" +
	"\vobjectGroup\x18\x02 \x03(\tR\vobjectGroup\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\".\n" +
	"\x16DeleteOutdatedDataResp\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\"\x89\x01\n" +
	"\x11FcmUpdateTokenReq\x12\x1e\n" +
	"\n" +
	"platformID\x18\x01 \x01(\x05R\n" +
	"platformID\x12\x1a\n" +
	"\bfcmToken\x18\x02 \x01(\tR\bfcmToken\x12\x18\n" +
	"\aaccount\x18\x03 \x01(\tR\aaccount\x12\x1e\n" +
	"\n" +
	"expireTime\x18\x04 \x01(\x03R\n" +
	"expireTime\"\x14\n" +
	"\x12FcmUpdateTokenResp\"P\n" +
	"\x0eSetAppBadgeReq\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\x12&\n" +
	"\x0eappUnreadCount\x18\x02 \x01(\x05R\x0eappUnreadCount\"\x11\n" +
	"\x0fSetAppBadgeResp\"7\n" +
	"\afileURL\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x10\n" +
	"\x03URL\x18\x02 \x01(\tR\x03URL\"\xac\x01\n" +
	"\rUploadLogsReq\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\x05R\bplatform\x121\n" +
	"\bfileURLs\x18\x02 \x03(\v2\x15.openim.third.fileURLR\bfileURLs\x12\"\n" +
	"\fappFramework\x18\x03 \x01(\tR\fappFramework\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x12\x0e\n" +
	"\x02ex\x18\x04 \x01(\tR\x02ex\"\x10\n" +
	"\x0eUploadLogsResp\"'\n" +
	"\rDeleteLogsReq\x12\x16\n" +
	"\x06logIDs\x18\x01 \x03(\tR\x06logIDs\"\x10\n" +
	"\x0eDeleteLogsResp\"\xa2\x01\n" +
	"\rSearchLogsReq\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12\x1c\n" +
	"\tstartTime\x18\x02 \x01(\x03R\tstartTime\x12\x18\n" +
	"\aendTime\x18\x03 \x01(\x03R\aendTime\x12?\n" +
	"\n" +
	"pagination\x18\x04 \x01(\v2\x1f.openim.sdkws.RequestPaginationR\n" +
	"pagination\"\x87\x02\n" +
	"\aLogInfo\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x1e\n" +
	"\n" +
	"createTime\x18\x04 \x01(\x03R\n" +
	"createTime\x12\x1a\n" +
	"\bnickname\x18\x05 \x01(\tR\bnickname\x12\x14\n" +
	"\x05logID\x18\x06 \x01(\tR\x05logID\x12\x1a\n" +
	"\bfilename\x18\a \x01(\tR\bfilename\x12\x1e\n" +
	"\n" +
	"systemType\x18\b \x01(\tR\n" +
	"systemType\x12\x0e\n" +
	"\x02ex\x18\t \x01(\tR\x02ex\x12\x18\n" +
	"\aversion\x18\n" +
	" \x01(\tR\aversion\"[\n" +
	"\x0eSearchLogsResp\x123\n" +
	"\tlogsInfos\x18\x01 \x03(\v2\x15.openim.third.LogInfoR\tlogsInfos\x12\x14\n" +
	"\x05total\x18\x02 \x01(\rR\x05total2\x8c\t\n" +
	"\x05third\x12D\n" +
	"\tPartLimit\x12\x1a.openim.third.PartLimitReq\x1a\x1b.openim.third.PartLimitResp\x12A\n" +
	"\bPartSize\x12\x19.openim.third.PartSizeReq\x1a\x1a.openim.third.PartSizeResp\x12n\n" +
	"\x17InitiateMultipartUpload\x12(.openim.third.InitiateMultipartUploadReq\x1a).openim.third.InitiateMultipartUploadResp\x12A\n" +
	"\bAuthSign\x12\x19.openim.third.AuthSignReq\x1a\x1a.openim.third.AuthSignResp\x12n\n" +
	"\x17CompleteMultipartUpload\x12(.openim.third.CompleteMultipartUploadReq\x1a).openim.third.CompleteMultipartUploadResp\x12D\n" +
	"\tAccessURL\x12\x1a.openim.third.AccessURLReq\x1a\x1b.openim.third.AccessURLResp\x12Y\n" +
	"\x10InitiateFormData\x12!.openim.third.InitiateFormDataReq\x1a\".openim.third.InitiateFormDataResp\x12Y\n" +
	"\x10CompleteFormData\x12!.openim.third.CompleteFormDataReq\x1a\".openim.third.CompleteFormDataResp\x12_\n" +
	"\x12DeleteOutdatedData\x12#.openim.third.DeleteOutdatedDataReq\x1a$.openim.third.DeleteOutdatedDataResp\x12S\n" +
	"\x0eFcmUpdateToken\x12\x1f.openim.third.FcmUpdateTokenReq\x1a .openim.third.FcmUpdateTokenResp\x12J\n" +
	"\vSetAppBadge\x12\x1c.openim.third.SetAppBadgeReq\x1a\x1d.openim.third.SetAppBadgeResp\x12G\n" +
	"\n" +
	"UploadLogs\x12\x1b.openim.third.UploadLogsReq\x1a\x1c.openim.third.UploadLogsResp\x12G\n" +
	"\n" +
	"DeleteLogs\x12\x1b.openim.third.DeleteLogsReq\x1a\x1c.openim.third.DeleteLogsResp\x12G\n" +
	"\n" +
	"SearchLogs\x12\x1b.openim.third.SearchLogsReq\x1a\x1c.openim.third.SearchLogsRespB%Z#github.com/openimsdk/protocol/thirdb\x06proto3"

var (
	file_third_third_proto_rawDescOnce sync.Once
	file_third_third_proto_rawDescData []byte
)

func file_third_third_proto_rawDescGZIP() []byte {
	file_third_third_proto_rawDescOnce.Do(func() {
		file_third_third_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_third_third_proto_rawDesc), len(file_third_third_proto_rawDesc)))
	})
	return file_third_third_proto_rawDescData
}

var file_third_third_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_third_third_proto_goTypes = []any{
	(*KeyValues)(nil),                   // 0: openim.third.KeyValues
	(*SignPart)(nil),                    // 1: openim.third.SignPart
	(*AuthSignParts)(nil),               // 2: openim.third.AuthSignParts
	(*PartLimitReq)(nil),                // 3: openim.third.PartLimitReq
	(*PartLimitResp)(nil),               // 4: openim.third.PartLimitResp
	(*PartSizeReq)(nil),                 // 5: openim.third.PartSizeReq
	(*PartSizeResp)(nil),                // 6: openim.third.PartSizeResp
	(*InitiateMultipartUploadReq)(nil),  // 7: openim.third.InitiateMultipartUploadReq
	(*UploadInfo)(nil),                  // 8: openim.third.UploadInfo
	(*InitiateMultipartUploadResp)(nil), // 9: openim.third.InitiateMultipartUploadResp
	(*AuthSignReq)(nil),                 // 10: openim.third.AuthSignReq
	(*AuthSignResp)(nil),                // 11: openim.third.AuthSignResp
	(*CompleteMultipartUploadReq)(nil),  // 12: openim.third.CompleteMultipartUploadReq
	(*CompleteMultipartUploadResp)(nil), // 13: openim.third.CompleteMultipartUploadResp
	(*AccessURLReq)(nil),                // 14: openim.third.AccessURLReq
	(*AccessURLResp)(nil),               // 15: openim.third.AccessURLResp
	(*InitiateFormDataReq)(nil),         // 16: openim.third.InitiateFormDataReq
	(*InitiateFormDataResp)(nil),        // 17: openim.third.InitiateFormDataResp
	(*CompleteFormDataReq)(nil),         // 18: openim.third.CompleteFormDataReq
	(*CompleteFormDataResp)(nil),        // 19: openim.third.CompleteFormDataResp
	(*DeleteOutdatedDataReq)(nil),       // 20: openim.third.DeleteOutdatedDataReq
	(*DeleteOutdatedDataResp)(nil),      // 21: openim.third.DeleteOutdatedDataResp
	(*FcmUpdateTokenReq)(nil),           // 22: openim.third.FcmUpdateTokenReq
	(*FcmUpdateTokenResp)(nil),          // 23: openim.third.FcmUpdateTokenResp
	(*SetAppBadgeReq)(nil),              // 24: openim.third.SetAppBadgeReq
	(*SetAppBadgeResp)(nil),             // 25: openim.third.SetAppBadgeResp
	(*FileURL)(nil),                     // 26: openim.third.fileURL
	(*UploadLogsReq)(nil),               // 27: openim.third.UploadLogsReq
	(*UploadLogsResp)(nil),              // 28: openim.third.UploadLogsResp
	(*DeleteLogsReq)(nil),               // 29: openim.third.DeleteLogsReq
	(*DeleteLogsResp)(nil),              // 30: openim.third.DeleteLogsResp
	(*SearchLogsReq)(nil),               // 31: openim.third.SearchLogsReq
	(*LogInfo)(nil),                     // 32: openim.third.LogInfo
	(*SearchLogsResp)(nil),              // 33: openim.third.SearchLogsResp
	nil,                                 // 34: openim.third.AccessURLReq.QueryEntry
	nil,                                 // 35: openim.third.InitiateFormDataResp.FormDataEntry
	(*sdkws.RequestPagination)(nil),     // 36: openim.sdkws.RequestPagination
}
var file_third_third_proto_depIdxs = []int32{
	0,  // 0: openim.third.SignPart.query:type_name -> openim.third.KeyValues
	0,  // 1: openim.third.SignPart.header:type_name -> openim.third.KeyValues
	0,  // 2: openim.third.AuthSignParts.query:type_name -> openim.third.KeyValues
	0,  // 3: openim.third.AuthSignParts.header:type_name -> openim.third.KeyValues
	1,  // 4: openim.third.AuthSignParts.parts:type_name -> openim.third.SignPart
	2,  // 5: openim.third.UploadInfo.sign:type_name -> openim.third.AuthSignParts
	8,  // 6: openim.third.InitiateMultipartUploadResp.upload:type_name -> openim.third.UploadInfo
	0,  // 7: openim.third.AuthSignResp.query:type_name -> openim.third.KeyValues
	0,  // 8: openim.third.AuthSignResp.header:type_name -> openim.third.KeyValues
	1,  // 9: openim.third.AuthSignResp.parts:type_name -> openim.third.SignPart
	34, // 10: openim.third.AccessURLReq.query:type_name -> openim.third.AccessURLReq.QueryEntry
	0,  // 11: openim.third.InitiateFormDataResp.header:type_name -> openim.third.KeyValues
	35, // 12: openim.third.InitiateFormDataResp.formData:type_name -> openim.third.InitiateFormDataResp.FormDataEntry
	26, // 13: openim.third.UploadLogsReq.fileURLs:type_name -> openim.third.fileURL
	36, // 14: openim.third.SearchLogsReq.pagination:type_name -> openim.sdkws.RequestPagination
	32, // 15: openim.third.SearchLogsResp.logsInfos:type_name -> openim.third.LogInfo
	3,  // 16: openim.third.third.PartLimit:input_type -> openim.third.PartLimitReq
	5,  // 17: openim.third.third.PartSize:input_type -> openim.third.PartSizeReq
	7,  // 18: openim.third.third.InitiateMultipartUpload:input_type -> openim.third.InitiateMultipartUploadReq
	10, // 19: openim.third.third.AuthSign:input_type -> openim.third.AuthSignReq
	12, // 20: openim.third.third.CompleteMultipartUpload:input_type -> openim.third.CompleteMultipartUploadReq
	14, // 21: openim.third.third.AccessURL:input_type -> openim.third.AccessURLReq
	16, // 22: openim.third.third.InitiateFormData:input_type -> openim.third.InitiateFormDataReq
	18, // 23: openim.third.third.CompleteFormData:input_type -> openim.third.CompleteFormDataReq
	20, // 24: openim.third.third.DeleteOutdatedData:input_type -> openim.third.DeleteOutdatedDataReq
	22, // 25: openim.third.third.FcmUpdateToken:input_type -> openim.third.FcmUpdateTokenReq
	24, // 26: openim.third.third.SetAppBadge:input_type -> openim.third.SetAppBadgeReq
	27, // 27: openim.third.third.UploadLogs:input_type -> openim.third.UploadLogsReq
	29, // 28: openim.third.third.DeleteLogs:input_type -> openim.third.DeleteLogsReq
	31, // 29: openim.third.third.SearchLogs:input_type -> openim.third.SearchLogsReq
	4,  // 30: openim.third.third.PartLimit:output_type -> openim.third.PartLimitResp
	6,  // 31: openim.third.third.PartSize:output_type -> openim.third.PartSizeResp
	9,  // 32: openim.third.third.InitiateMultipartUpload:output_type -> openim.third.InitiateMultipartUploadResp
	11, // 33: openim.third.third.AuthSign:output_type -> openim.third.AuthSignResp
	13, // 34: openim.third.third.CompleteMultipartUpload:output_type -> openim.third.CompleteMultipartUploadResp
	15, // 35: openim.third.third.AccessURL:output_type -> openim.third.AccessURLResp
	17, // 36: openim.third.third.InitiateFormData:output_type -> openim.third.InitiateFormDataResp
	19, // 37: openim.third.third.CompleteFormData:output_type -> openim.third.CompleteFormDataResp
	21, // 38: openim.third.third.DeleteOutdatedData:output_type -> openim.third.DeleteOutdatedDataResp
	23, // 39: openim.third.third.FcmUpdateToken:output_type -> openim.third.FcmUpdateTokenResp
	25, // 40: openim.third.third.SetAppBadge:output_type -> openim.third.SetAppBadgeResp
	28, // 41: openim.third.third.UploadLogs:output_type -> openim.third.UploadLogsResp
	30, // 42: openim.third.third.DeleteLogs:output_type -> openim.third.DeleteLogsResp
	33, // 43: openim.third.third.SearchLogs:output_type -> openim.third.SearchLogsResp
	30, // [30:44] is the sub-list for method output_type
	16, // [16:30] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_third_third_proto_init() }
func file_third_third_proto_init() {
	if File_third_third_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_third_third_proto_rawDesc), len(file_third_third_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_third_third_proto_goTypes,
		DependencyIndexes: file_third_third_proto_depIdxs,
		MessageInfos:      file_third_third_proto_msgTypes,
	}.Build()
	File_third_third_proto = out.File
	file_third_third_proto_goTypes = nil
	file_third_third_proto_depIdxs = nil
}
