package conversation

import (
	"github.com/openimsdk/protocol/rpccall"
	"google.golang.org/grpc"
)

func InitConversation(conn *grpc.ClientConn) {
	GetConversationCaller.SetConn(conn)
	GetSortedConversationListCaller.SetConn(conn)
	GetAllConversationsCaller.SetConn(conn)
	GetConversationsCaller.SetConn(conn)
	SetConversationCaller.SetConn(conn)
	GetRecvMsgNotNotifyUserIDsCaller.SetConn(conn)
	CreateSingleChatConversationsCaller.SetConn(conn)
	CreateGroupChatConversationsCaller.SetConn(conn)
	SetConversationMaxSeqCaller.SetConn(conn)
	SetConversationMinSeqCaller.SetConn(conn)
	GetConversationIDsCaller.SetConn(conn)
	SetConversationsCaller.SetConn(conn)
	GetUserConversationIDsHashCaller.SetConn(conn)
	GetConversationsByConversationIDCaller.SetConn(conn)
	GetConversationOfflinePushUserIDsCaller.SetConn(conn)
	GetConversationNotReceiveMessageUserIDsCaller.SetConn(conn)
	UpdateConversationCaller.SetConn(conn)
	GetFullOwnerConversationIDsCaller.SetConn(conn)
	GetIncrementalConversationCaller.SetConn(conn)
	GetOwnerConversationCaller.SetConn(conn)
	GetConversationsNeedClearMsgCaller.SetConn(conn)
	GetNotNotifyConversationIDsCaller.SetConn(conn)
	GetPinnedConversationIDsCaller.SetConn(conn)
}

var (
	GetConversationCaller                         = rpccall.NewRpcCaller[GetConversationReq, GetConversationResp](Conversation_GetConversation_FullMethodName)
	GetSortedConversationListCaller               = rpccall.NewRpcCaller[GetSortedConversationListReq, GetSortedConversationListResp](Conversation_GetSortedConversationList_FullMethodName)
	GetAllConversationsCaller                     = rpccall.NewRpcCaller[GetAllConversationsReq, GetAllConversationsResp](Conversation_GetAllConversations_FullMethodName)
	GetConversationsCaller                        = rpccall.NewRpcCaller[GetConversationsReq, GetConversationsResp](Conversation_GetConversations_FullMethodName)
	SetConversationCaller                         = rpccall.NewRpcCaller[SetConversationReq, SetConversationResp](Conversation_SetConversation_FullMethodName)
	GetRecvMsgNotNotifyUserIDsCaller              = rpccall.NewRpcCaller[GetRecvMsgNotNotifyUserIDsReq, GetRecvMsgNotNotifyUserIDsResp](Conversation_GetRecvMsgNotNotifyUserIDs_FullMethodName)
	CreateSingleChatConversationsCaller           = rpccall.NewRpcCaller[CreateSingleChatConversationsReq, CreateSingleChatConversationsResp](Conversation_CreateSingleChatConversations_FullMethodName)
	CreateGroupChatConversationsCaller            = rpccall.NewRpcCaller[CreateGroupChatConversationsReq, CreateGroupChatConversationsResp](Conversation_CreateGroupChatConversations_FullMethodName)
	SetConversationMaxSeqCaller                   = rpccall.NewRpcCaller[SetConversationMaxSeqReq, SetConversationMaxSeqResp](Conversation_SetConversationMaxSeq_FullMethodName)
	SetConversationMinSeqCaller                   = rpccall.NewRpcCaller[SetConversationMinSeqReq, SetConversationMinSeqResp](Conversation_SetConversationMinSeq_FullMethodName)
	GetConversationIDsCaller                      = rpccall.NewRpcCaller[GetConversationIDsReq, GetConversationIDsResp](Conversation_GetConversationIDs_FullMethodName)
	SetConversationsCaller                        = rpccall.NewRpcCaller[SetConversationsReq, SetConversationsResp](Conversation_SetConversations_FullMethodName)
	GetUserConversationIDsHashCaller              = rpccall.NewRpcCaller[GetUserConversationIDsHashReq, GetUserConversationIDsHashResp](Conversation_GetUserConversationIDsHash_FullMethodName)
	GetConversationsByConversationIDCaller        = rpccall.NewRpcCaller[GetConversationsByConversationIDReq, GetConversationsByConversationIDResp](Conversation_GetConversationsByConversationID_FullMethodName)
	GetConversationOfflinePushUserIDsCaller       = rpccall.NewRpcCaller[GetConversationOfflinePushUserIDsReq, GetConversationOfflinePushUserIDsResp](Conversation_GetConversationOfflinePushUserIDs_FullMethodName)
	GetConversationNotReceiveMessageUserIDsCaller = rpccall.NewRpcCaller[GetConversationNotReceiveMessageUserIDsReq, GetConversationNotReceiveMessageUserIDsResp](Conversation_GetConversationNotReceiveMessageUserIDs_FullMethodName)
	UpdateConversationCaller                      = rpccall.NewRpcCaller[UpdateConversationReq, UpdateConversationResp](Conversation_UpdateConversation_FullMethodName)
	GetFullOwnerConversationIDsCaller             = rpccall.NewRpcCaller[GetFullOwnerConversationIDsReq, GetFullOwnerConversationIDsResp](Conversation_GetFullOwnerConversationIDs_FullMethodName)
	GetIncrementalConversationCaller              = rpccall.NewRpcCaller[GetIncrementalConversationReq, GetIncrementalConversationResp](Conversation_GetIncrementalConversation_FullMethodName)
	GetOwnerConversationCaller                    = rpccall.NewRpcCaller[GetOwnerConversationReq, GetOwnerConversationResp](Conversation_GetOwnerConversation_FullMethodName)
	GetConversationsNeedClearMsgCaller            = rpccall.NewRpcCaller[GetConversationsNeedClearMsgReq, GetConversationsNeedClearMsgResp](Conversation_GetConversationsNeedClearMsg_FullMethodName)
	GetNotNotifyConversationIDsCaller             = rpccall.NewRpcCaller[GetNotNotifyConversationIDsReq, GetNotNotifyConversationIDsResp](Conversation_GetNotNotifyConversationIDs_FullMethodName)
	GetPinnedConversationIDsCaller                = rpccall.NewRpcCaller[GetPinnedConversationIDsReq, GetPinnedConversationIDsResp](Conversation_GetPinnedConversationIDs_FullMethodName)
)
