// Copyright © 2023 OpenIM. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: push/push.proto

package push

import (
	sdkws "github.com/openimsdk/protocol/sdkws"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PushMsgReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MsgData        *sdkws.MsgData         `protobuf:"bytes,1,opt,name=msgData,proto3" json:"msgData"`
	ConversationID string                 `protobuf:"bytes,2,opt,name=conversationID,proto3" json:"conversationID"`
	UserIDs        []string               `protobuf:"bytes,3,rep,name=userIDs,proto3" json:"userIDs"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PushMsgReq) Reset() {
	*x = PushMsgReq{}
	mi := &file_push_push_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushMsgReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushMsgReq) ProtoMessage() {}

func (x *PushMsgReq) ProtoReflect() protoreflect.Message {
	mi := &file_push_push_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushMsgReq.ProtoReflect.Descriptor instead.
func (*PushMsgReq) Descriptor() ([]byte, []int) {
	return file_push_push_proto_rawDescGZIP(), []int{0}
}

func (x *PushMsgReq) GetMsgData() *sdkws.MsgData {
	if x != nil {
		return x.MsgData
	}
	return nil
}

func (x *PushMsgReq) GetConversationID() string {
	if x != nil {
		return x.ConversationID
	}
	return ""
}

func (x *PushMsgReq) GetUserIDs() []string {
	if x != nil {
		return x.UserIDs
	}
	return nil
}

type PushMsgResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushMsgResp) Reset() {
	*x = PushMsgResp{}
	mi := &file_push_push_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushMsgResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushMsgResp) ProtoMessage() {}

func (x *PushMsgResp) ProtoReflect() protoreflect.Message {
	mi := &file_push_push_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushMsgResp.ProtoReflect.Descriptor instead.
func (*PushMsgResp) Descriptor() ([]byte, []int) {
	return file_push_push_proto_rawDescGZIP(), []int{1}
}

type DelUserPushTokenReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID"`
	PlatformID    int32                  `protobuf:"varint,2,opt,name=platformID,proto3" json:"platformID"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelUserPushTokenReq) Reset() {
	*x = DelUserPushTokenReq{}
	mi := &file_push_push_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelUserPushTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelUserPushTokenReq) ProtoMessage() {}

func (x *DelUserPushTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_push_push_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelUserPushTokenReq.ProtoReflect.Descriptor instead.
func (*DelUserPushTokenReq) Descriptor() ([]byte, []int) {
	return file_push_push_proto_rawDescGZIP(), []int{2}
}

func (x *DelUserPushTokenReq) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *DelUserPushTokenReq) GetPlatformID() int32 {
	if x != nil {
		return x.PlatformID
	}
	return 0
}

type DelUserPushTokenResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelUserPushTokenResp) Reset() {
	*x = DelUserPushTokenResp{}
	mi := &file_push_push_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelUserPushTokenResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelUserPushTokenResp) ProtoMessage() {}

func (x *DelUserPushTokenResp) ProtoReflect() protoreflect.Message {
	mi := &file_push_push_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelUserPushTokenResp.ProtoReflect.Descriptor instead.
func (*DelUserPushTokenResp) Descriptor() ([]byte, []int) {
	return file_push_push_proto_rawDescGZIP(), []int{3}
}

var File_push_push_proto protoreflect.FileDescriptor

const file_push_push_proto_rawDesc = "" +
	"\n" +
	"\x0fpush/push.proto\x12\vopenim.push\x1a\x11sdkws/sdkws.proto\"\x7f\n" +
	"\n" +
	"PushMsgReq\x12/\n" +
	"\amsgData\x18\x01 \x01(\v2\x15.openim.sdkws.MsgDataR\amsgData\x12&\n" +
	"\x0econversationID\x18\x02 \x01(\tR\x0econversationID\x12\x18\n" +
	"\auserIDs\x18\x03 \x03(\tR\auserIDs\"\r\n" +
	"\vPushMsgResp\"M\n" +
	"\x13DelUserPushTokenReq\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\tR\x06userID\x12\x1e\n" +
	"\n" +
	"platformID\x18\x02 \x01(\x05R\n" +
	"platformID\"\x16\n" +
	"\x14DelUserPushTokenResp2\xa7\x01\n" +
	"\x0ePushMsgService\x12<\n" +
	"\aPushMsg\x12\x17.openim.push.PushMsgReq\x1a\x18.openim.push.PushMsgResp\x12W\n" +
	"\x10DelUserPushToken\x12 .openim.push.DelUserPushTokenReq\x1a!.openim.push.DelUserPushTokenRespB$Z\"github.com/openimsdk/protocol/pushb\x06proto3"

var (
	file_push_push_proto_rawDescOnce sync.Once
	file_push_push_proto_rawDescData []byte
)

func file_push_push_proto_rawDescGZIP() []byte {
	file_push_push_proto_rawDescOnce.Do(func() {
		file_push_push_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_push_push_proto_rawDesc), len(file_push_push_proto_rawDesc)))
	})
	return file_push_push_proto_rawDescData
}

var file_push_push_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_push_push_proto_goTypes = []any{
	(*PushMsgReq)(nil),           // 0: openim.push.PushMsgReq
	(*PushMsgResp)(nil),          // 1: openim.push.PushMsgResp
	(*DelUserPushTokenReq)(nil),  // 2: openim.push.DelUserPushTokenReq
	(*DelUserPushTokenResp)(nil), // 3: openim.push.DelUserPushTokenResp
	(*sdkws.MsgData)(nil),        // 4: openim.sdkws.MsgData
}
var file_push_push_proto_depIdxs = []int32{
	4, // 0: openim.push.PushMsgReq.msgData:type_name -> openim.sdkws.MsgData
	0, // 1: openim.push.PushMsgService.PushMsg:input_type -> openim.push.PushMsgReq
	2, // 2: openim.push.PushMsgService.DelUserPushToken:input_type -> openim.push.DelUserPushTokenReq
	1, // 3: openim.push.PushMsgService.PushMsg:output_type -> openim.push.PushMsgResp
	3, // 4: openim.push.PushMsgService.DelUserPushToken:output_type -> openim.push.DelUserPushTokenResp
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_push_push_proto_init() }
func file_push_push_proto_init() {
	if File_push_push_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_push_push_proto_rawDesc), len(file_push_push_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_push_push_proto_goTypes,
		DependencyIndexes: file_push_push_proto_depIdxs,
		MessageInfos:      file_push_push_proto_msgTypes,
	}.Build()
	File_push_push_proto = out.File
	file_push_push_proto_goTypes = nil
	file_push_push_proto_depIdxs = nil
}
